	.file	"interrupt_handler.c"
	.stabs	"/home/hanguru/2011_project_original/lgdtv_vidan4110_fw_capp_project/software/vi_fw_project/",100,0,2,.Ltext0
	.stabs	"ucos/interrupt_handler.c",100,0,2,.Ltext0
.section .internalrom, "ax"
.Ltext0:
	.stabs	"gcc2_compiled.",60,0,0,0
	.stabs	"int:t(0,1)=r(0,1);-2147483648;2147483647;",128,0,0,0
	.stabs	"char:t(0,2)=r(0,2);0;127;",128,0,0,0
	.stabs	"long int:t(0,3)=r(0,3);-2147483648;2147483647;",128,0,0,0
	.stabs	"unsigned int:t(0,4)=r(0,4);0;037777777777;",128,0,0,0
	.stabs	"long unsigned int:t(0,5)=r(0,5);0;037777777777;",128,0,0,0
	.stabs	"long long int:t(0,6)=@s64;r(0,6);01000000000000000000000;0777777777777777777777;",128,0,0,0
	.stabs	"long long unsigned int:t(0,7)=@s64;r(0,7);0;01777777777777777777777;",128,0,0,0
	.stabs	"short int:t(0,8)=@s16;r(0,8);-32768;32767;",128,0,0,0
	.stabs	"short unsigned int:t(0,9)=@s16;r(0,9);0;65535;",128,0,0,0
	.stabs	"signed char:t(0,10)=@s8;r(0,10);-128;127;",128,0,0,0
	.stabs	"unsigned char:t(0,11)=@s8;r(0,11);0;255;",128,0,0,0
	.stabs	"float:t(0,12)=r(0,1);4;0;",128,0,0,0
	.stabs	"double:t(0,13)=r(0,1);8;0;",128,0,0,0
	.stabs	"long double:t(0,14)=r(0,1);8;0;",128,0,0,0
	.stabs	"void:t(0,15)=(0,15)",128,0,0,0
	.stabs	"ucos/interrupt_handler.h",130,0,0,0
	.stabs	"ucos/task_manage.h",130,0,0,0
	.stabs	"ucos/ucos_ii.h",130,0,0,0
	.stabs	"ucos/os_cpu.h",130,0,0,0
	.stabs	"BOOLEAN:t(4,1)=(0,11)",128,0,9,0
	.stabs	"INT8U:t(4,2)=(0,11)",128,0,10,0
	.stabs	"INT8S:t(4,3)=(0,2)",128,0,11,0
	.stabs	"INT16U:t(4,4)=(0,9)",128,0,12,0
	.stabs	"INT16S:t(4,5)=(0,8)",128,0,13,0
	.stabs	"INT32U:t(4,6)=(0,5)",128,0,14,0
	.stabs	"INT32S:t(4,7)=(0,3)",128,0,15,0
	.stabs	"VBOOLEAN:t(4,8)=(4,9)=B(0,11)",128,0,16,0
	.stabs	"OS_STK:t(4,10)=(0,4)",128,0,17,0
	.stabs	"OS_CPU_SR:t(4,11)=(0,4)",128,0,18,0
	.stabn	162,0,0,0
	.stabs	"ucos/os_cfg.h",130,0,0,0
	.stabs	"OS_FLAGS:t(5,1)=(4,4)",128,0,112,0
	.stabn	162,0,0,0
	.stabs	"os_event:T(3,1)=s44OSEventType:(4,2),0,8;OSEventGrp:(4,2),8,8;OSEventCnt:(4,4),16,16;OSEventPtr:(3,2)=*(0,15),32,32;OSEventTbl:(3,3)=ar(3,4)=r(3,4);0;037777777777;;0;0;(4,2),64,8;OSEventName:(3,5)=ar(3,4);0;31;(0,2),72,256;;",128,0,0,0
	.stabs	"OS_EVENT:t(3,6)=(3,1)",128,0,257,0
	.stabs	"os_sem_data:T(3,7)=s4OSCnt:(4,4),0,16;OSEventTbl:(3,3),16,8;OSEventGrp:(4,2),24,8;;",128,0,0,0
	.stabs	"OS_SEM_DATA:t(3,8)=(3,7)",128,0,387,0
	.stabs	"os_stk_data:T(3,9)=s8OSFree:(4,6),0,32;OSUsed:(4,6),32,32;;",128,0,0,0
	.stabs	"OS_STK_DATA:t(3,10)=(3,9)",128,0,400,0
	.stabs	"os_tcb:T(3,11)=s96OSTCBStkPtr:(3,12)=*(4,10),0,32;OSTCBExtPtr:(3,2),32,32;OSTCBStkBottom:(3,12),64,32;OSTCBStkSize:(4,6),96,32;OSTCBOpt:(4,4),128,16;OSTCBId:(4,4),144,16;OSTCBNext:(3,13)=*(3,11),160,32;OSTCBPrev:(3,13),192,32;OSTCBEventPtr:(3,14)=*(3,6),224,32;OSTCBDly:(4,4),256,16;OSTCBStat:(4,2),272,8;OSTCBPendTO:(4,1),280,8;OSTCBPrio:(4,2),288,8;OSTCBX:(4,2),296,8;OSTCBY:(4,2),304,8;OSTCBBitX:(4,2),312,8;OSTCBBitY:(4,2),320,8;OSTCBDelReq:(4,2),328,8;OSTCBCtxSwCtr:(4,6),352,32;OSTCBCyclesTot:(4,6),384,32;OSTCBCyclesStart:(4,6),416,32;OSTCBStkBase:(3,12),448,32;OSTCBStkUsed:(4,6),480,32;OSTCBTaskName:(3,5),512,256;;",128,0,0,0
	.stabs	"OS_TCB:t(3,15)=(3,11)",128,0,464,0
	.stabn	162,0,0,0
	.stabn	162,0,0,0
	.stabn	162,0,0,0
	.stabs	"interface/usb.h",130,0,0,0
	.stabs	"EndpointDescriptorObj:t(6,1)=(6,2)=s24num:(0,1),0,32;enabled:(0,1),32,32;type:(0,1),64,32;maxpacketsize:(0,1),96,32;pid:(0,1),128,32;dir:(0,1),160,32;;",128,0,427,0
	.stabs	"IntfDescriptorObj:t(6,3)=(6,4)=s12Class:(0,1),0,32;SubClass:(0,1),32,32;Protocol:(0,1),64,32;;",128,0,433,0
	.stabs	" :T(6,5)=eMSD_BOT:0,MSD_CBI:1,;",128,0,0,0
	.stabs	"MsdDeviceType:t(6,6)=(6,5)",128,0,438,0
	.stabs	" :T(6,7)=eDISCONNECTED:0,FS_CONNECT:1,HS_CONNECT:2,LS_CONNECT:3,SUSPENDED:4,RESUMING:5,;",128,0,0,0
	.stabs	"UsbConnectionType:t(6,8)=(6,7)",128,0,447,0
	.stabs	"tUsbHostObj:t(6,9)=(6,10)=s164VID:(0,1),0,32;PID:(0,1),32,32;DevClass:(0,1),64,32;Intf:(6,3),96,96;Address:(0,1),192,32;NumEp:(0,1),224,32;enumerated:(0,1),256,32;resume_complete:(0,1),288,32;suspended:(0,1),320,32;configured:(0,1),352,32;OtgSupport:(0,1),384,32;InterfaceType:(0,1),416,32;EP0:(6,1),448,192;EPIIn:(6,1),640,192;EPBIn:(6,1),832,192;EPBOut:(6,1),1024,192;EPcsw:(6,11)=*(6,1),1216,32;connection:(6,8),1248,32;MsdType:(6,6),1280,32;;",128,0,469,0
	.stabs	" :T(6,12)=eDEFAULT:0,B_IDLE:1,B_SRP_INIT:2,B_PERIPHERAL:3,B_WAIT_ACON:4,B_HOST:5,A_IDLE:6,A_WAIT_VRISE:7,A_WAIT_BCON:8,A_HOST:9,A_HOST_REG:10,A_SUSPEND:11,A_RESUME:12,A_PERIPHERAL:13,A_WAIT_VFALL:14,A_VBUS_ERR:15,;",128,0,0,0
	.stabs	"tOtgStateType:t(6,13)=(6,12)",128,0,488,0
	.stabs	" :T(6,14)=eDEV_UNCONFIGURED:0,DEV_ADDRESSED:1,DEV_CONFIGURED:2,DEV_SUSPENDED:3,DEV_RESUME:4,HST_UNCONNECTED:5,HST_CONNECTED:6,;",128,0,0,0
	.stabs	"tUsbStateType:t(6,15)=(6,14)",128,0,498,0
	.stabs	"tOtgInfoObj:t(6,16)=(6,17)=s24SrpSupport:(0,1),0,32;HnpSupport:(0,1),32,32;hnp_enabled:(0,1),64,32;b_hnp_enable:(0,1),96,32;a_hnp_support:(0,1),128,32;a_alt_hnp_support:(0,1),160,32;;",128,0,507,0
	.stabs	"tUsbDeviceObj:t(6,18)=(6,19)=s20set_halt:(0,1),0,32;Device_Config_Value:(0,1),32,32;ep0_max_pl:(0,1),64,32;max_pl:(0,1),96,32;set_remote_wakeup:(0,1),128,32;;",128,0,515,0
	.stabs	"tUsbSystemObj:t(6,20)=(6,21)=s240DeviceState:(6,15),0,32;MainState:(6,13),32,32;otg_support:(0,1),64,32;is_host:(0,1),96,32;RegularHost:(0,1),128,32;gpout_shadow:(0,1),160,32;rxBuffer:(0,4),192,32;txBuffer:(0,4),224,32;OtgConfig:(6,16),256,192;Host:(6,9),448,1312;Dev:(6,18),1760,160;;",128,0,529,0
	.stabn	162,0,0,0
.proc _OpenRiscEnableTimerInt
	.stabs	"OpenRiscEnableTimerInt:F(0,15)",36,0,18,_OpenRiscEnableTimerInt
	.stabs	"tick:P(4,6)",64,0,18,3
	.global _OpenRiscEnableTimerInt
	.type	_OpenRiscEnableTimerInt, @function
_OpenRiscEnableTimerInt:
	.stabd	46,0,0
	.stabn	68,0,18,.LM0-.LFBB1
.LM0:
.LFBB1:
	.stabn	68,0,20,.LM1-.LFBB1
.LM1:
	b.addi 	r6,r0,20481	  # movsi imm I
	b.movi 	r7,0	     # movsi imm P
	l.mtspr r6,r7,0
	.stabn	68,0,25,.LM2-.LFBB1
.LM2:
	b.addi 	r7,r0,20480	  # movsi imm I
	b.andi  	r3,r3,268435455
	b.ori   	r3,r3,1610612736
	l.mtspr r7,r3,0
.LBB2:
	.stabn	68,0,27,.LM3-.LFBB1
.LM3:
	b.ori  	r7,r0,17	  # movsi imm J
	l.mfspr r7,r7,0
.LBE2:
	b.ori  	r6,r0,17	  # movsi imm J
	b.ori   	r7,r7,2
	l.mtspr r6,r7,0
	.stabn	68,0,28,.LM4-.LFBB1
.LM4:
	b.jr    	r9
	.size	_OpenRiscEnableTimerInt, .-_OpenRiscEnableTimerInt
	.stabs	"val:r(0,4)",64,0,27,7
	.stabn	192,0,0,.LBB2-.LFBB1
	.stabn	224,0,0,.LBE2-.LFBB1
.Lscope1:
	.stabs	"",36,0,0,.Lscope1-.LFBB1
	.stabd	78,0,0
.proc _OpenRiscDisableTimerInt
	.stabs	"OpenRiscDisableTimerInt:F(0,15)",36,0,30,_OpenRiscDisableTimerInt
	.global _OpenRiscDisableTimerInt
	.type	_OpenRiscDisableTimerInt, @function
_OpenRiscDisableTimerInt:
	.stabd	46,0,0
	.stabn	68,0,30,.LM5-.LFBB2
.LM5:
.LFBB2:
	.stabn	68,0,32,.LM6-.LFBB2
.LM6:
	b.addi 	r6,r0,20481	  # movsi imm I
	b.movi 	r7,0	     # movsi imm P
	l.mtspr r6,r7,0
	.stabn	68,0,37,.LM7-.LFBB2
.LM7:
	b.addi 	r6,r0,20480	  # movsi imm I
	l.mtspr r6,r7,0
.LBB3:
	.stabn	68,0,39,.LM8-.LFBB2
.LM8:
	b.ori  	r7,r0,17	  # movsi imm J
	l.mfspr r7,r7,0
.LBE3:
	b.ori  	r6,r0,17	  # movsi imm J
	b.andi  	r7,r7,-3
	l.mtspr r6,r7,0
	.stabn	68,0,40,.LM9-.LFBB2
.LM9:
	b.jr    	r9
	.size	_OpenRiscDisableTimerInt, .-_OpenRiscDisableTimerInt
	.stabs	"val:r(0,4)",64,0,39,7
	.stabn	192,0,0,.LBB3-.LFBB2
	.stabn	224,0,0,.LBE3-.LFBB2
.Lscope2:
	.stabs	"",36,0,0,.Lscope2-.LFBB2
	.stabd	78,0,0
.proc _OpenRiscTimerRestart
	.stabs	"OpenRiscTimerRestart:F(0,15)",36,0,42,_OpenRiscTimerRestart
	.global _OpenRiscTimerRestart
	.type	_OpenRiscTimerRestart, @function
_OpenRiscTimerRestart:
	.stabd	46,0,0
	.stabn	68,0,42,.LM10-.LFBB3
.LM10:
.LFBB3:
.LBB4:
	.stabn	68,0,43,.LM11-.LFBB3
.LM11:
	b.addi 	r7,r0,20480	  # movsi imm I
	l.mfspr r7,r7,0
.LBE4:
	b.addi 	r6,r0,20480	  # movsi imm I
	b.andi  	r7,r7,1073741823
	b.ori   	r7,r7,1073741824
	l.mtspr r6,r7,0
	.stabn	68,0,44,.LM12-.LFBB3
.LM12:
	b.jr    	r9
	.size	_OpenRiscTimerRestart, .-_OpenRiscTimerRestart
	.stabs	"val:r(0,4)",64,0,43,7
	.stabn	192,0,0,.LBB4-.LFBB3
	.stabn	224,0,0,.LBE4-.LFBB3
.Lscope3:
	.stabs	"",36,0,0,.Lscope3-.LFBB3
	.stabd	78,0,0
.proc _OpenRiscTimerPause
	.stabs	"OpenRiscTimerPause:F(0,15)",36,0,46,_OpenRiscTimerPause
	.global _OpenRiscTimerPause
	.type	_OpenRiscTimerPause, @function
_OpenRiscTimerPause:
	.stabd	46,0,0
	.stabn	68,0,46,.LM13-.LFBB4
.LM13:
.LFBB4:
.LBB5:
	.stabn	68,0,47,.LM14-.LFBB4
.LM14:
	b.addi 	r7,r0,20480	  # movsi imm I
	l.mfspr r7,r7,0
.LBE5:
	b.addi 	r6,r0,20480	  # movsi imm I
	b.andi  	r7,r7,1073741823
	l.mtspr r6,r7,0
	.stabn	68,0,48,.LM15-.LFBB4
.LM15:
	b.jr    	r9
	.size	_OpenRiscTimerPause, .-_OpenRiscTimerPause
	.stabs	"val:r(0,4)",64,0,47,7
	.stabn	192,0,0,.LBB5-.LFBB4
	.stabn	224,0,0,.LBE5-.LFBB4
.Lscope4:
	.stabs	"",36,0,0,.Lscope4-.LFBB4
	.stabd	78,0,0
.proc _OpenRiscEnableInt
	.stabs	"OpenRiscEnableInt:F(0,15)",36,0,55,_OpenRiscEnableInt
	.global _OpenRiscEnableInt
	.type	_OpenRiscEnableInt, @function
_OpenRiscEnableInt:
	.stabd	46,0,0
	.stabn	68,0,55,.LM16-.LFBB5
.LM16:
.LFBB5:
.LBB6:
	.stabn	68,0,57,.LM17-.LFBB5
.LM17:
	b.ori  	r7,r0,17	  # movsi imm J
	l.mfspr r7,r7,0
.LBE6:
	b.ori  	r6,r0,17	  # movsi imm J
	b.ori   	r7,r7,4
	l.mtspr r6,r7,0
	.stabn	68,0,59,.LM18-.LFBB5
.LM18:
	b.jr    	r9
	.size	_OpenRiscEnableInt, .-_OpenRiscEnableInt
	.stabs	"val:r(0,4)",64,0,57,7
	.stabn	192,0,0,.LBB6-.LFBB5
	.stabn	224,0,0,.LBE6-.LFBB5
.Lscope5:
	.stabs	"",36,0,0,.Lscope5-.LFBB5
	.stabd	78,0,0
.proc _OpenRiscDisableInt
	.stabs	"OpenRiscDisableInt:F(0,15)",36,0,61,_OpenRiscDisableInt
	.global _OpenRiscDisableInt
	.type	_OpenRiscDisableInt, @function
_OpenRiscDisableInt:
	.stabd	46,0,0
	.stabn	68,0,61,.LM19-.LFBB6
.LM19:
.LFBB6:
.LBB7:
	.stabn	68,0,63,.LM20-.LFBB6
.LM20:
	b.ori  	r7,r0,17	  # movsi imm J
	l.mfspr r7,r7,0
.LBE7:
	b.ori  	r6,r0,17	  # movsi imm J
	b.andi  	r7,r7,-5
	l.mtspr r6,r7,0
	.stabn	68,0,65,.LM21-.LFBB6
.LM21:
	b.jr    	r9
	.size	_OpenRiscDisableInt, .-_OpenRiscDisableInt
	.stabs	"val:r(0,4)",64,0,63,7
	.stabn	192,0,0,.LBB7-.LFBB6
	.stabn	224,0,0,.LBE7-.LFBB6
.Lscope6:
	.stabs	"",36,0,0,.Lscope6-.LFBB6
	.stabd	78,0,0
.proc _IntEnable
	.stabs	"IntEnable:F(0,15)",36,0,67,_IntEnable
	.stabs	"type:P(4,6)",64,0,67,3
	.global _IntEnable
	.type	_IntEnable, @function
_IntEnable:
	.stabd	46,0,0
	.stabn	68,0,67,.LM22-.LFBB7
.LM22:
.LFBB7:
.LBB8:
	.stabn	68,0,69,.LM23-.LFBB7
.LM23:
	b.addi 	r7,r0,18432	  # movsi imm I
	l.mfspr r7,r7,0
.LBE8:
	b.addi 	r6,r0,18432	  # movsi imm I
	b.or    	r7,r7,r3
	l.mtspr r6,r7,0
	.stabn	68,0,71,.LM24-.LFBB7
.LM24:
	b.jr    	r9
	.size	_IntEnable, .-_IntEnable
	.stabs	"val:r(0,4)",64,0,69,7
	.stabn	192,0,0,.LBB8-.LFBB7
	.stabn	224,0,0,.LBE8-.LFBB7
.Lscope7:
	.stabs	"",36,0,0,.Lscope7-.LFBB7
	.stabd	78,0,0
.proc _IntDisable
	.stabs	"IntDisable:F(0,15)",36,0,73,_IntDisable
	.stabs	"type:P(4,6)",64,0,73,3
	.global _IntDisable
	.type	_IntDisable, @function
_IntDisable:
	.stabd	46,0,0
	.stabn	68,0,73,.LM25-.LFBB8
.LM25:
.LFBB8:
.LBB9:
	.stabn	68,0,75,.LM26-.LFBB8
.LM26:
	b.addi 	r7,r0,18432	  # movsi imm I
	l.mfspr r7,r7,0
.LBE9:
	b.addi 	r6,r0,18432	  # movsi imm I
	b.nand  	r3,r3,r3
	b.and   	r7,r7,r3
	l.mtspr r6,r7,0
	.stabn	68,0,77,.LM27-.LFBB8
.LM27:
	b.jr    	r9
	.size	_IntDisable, .-_IntDisable
	.stabs	"val:r(0,4)",64,0,75,7
	.stabn	192,0,0,.LBB9-.LFBB8
	.stabn	224,0,0,.LBE9-.LFBB8
.Lscope8:
	.stabs	"",36,0,0,.Lscope8-.LFBB8
	.stabd	78,0,0
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	"UNDEFINED INT\n"
.section .internalrom, "ax"
.proc _IntHandler
	.stabs	"IntHandler:F(0,15)",36,0,95,_IntHandler
	.global _IntHandler
	.type	_IntHandler, @function
_IntHandler:
	.stabd	46,0,0
	.stabn	68,0,95,.LM28-.LFBB9
.LM28:
.LFBB9:
	b.entri 	1,0
.LBB10:
	.stabn	68,0,97,.LM29-.LFBB9
.LM29:
	b.addi 	r7,r0,18434	  # movsi imm I
	l.mfspr r6,r7,0
.LBE10:
	bw.sw    	(_int_flag)(r0),r6	   # movsi store
	.stabn	68,0,98,.LM30-.LFBB9
.LM30:
	b.andi  	r7,r6,4096
	b.beqi  	r7,0,.L18
	.stabn	68,0,100,.LM31-.LFBB9
.LM31:
	b.jal  	_i2s_interrupt_handler
	.stabn	68,0,102,.LM32-.LFBB9
.LM32:
	b.addi 	r6,r0,18434	  # movsi imm I
	bw.lwz   	r7,(_int_flag)(r0)	    # movsi load
	b.andi  	r7,r7,-4097
	l.mtspr r6,r7,0
	b.j    	.L20
.L18:
	.stabn	68,0,103,.LM33-.LFBB9
.LM33:
	b.andi  	r7,r6,2048
	b.beqi  	r7,0,.L21
	.stabn	68,0,105,.LM34-.LFBB9
.LM34:
	b.jal  	_IntHandlerGPIO
	.stabn	68,0,107,.LM35-.LFBB9
.LM35:
	b.addi 	r6,r0,18434	  # movsi imm I
	bw.lwz   	r7,(_int_flag)(r0)	    # movsi load
	b.andi  	r7,r7,-2049
	l.mtspr r6,r7,0
	b.j    	.L20
.L21:
	.stabn	68,0,108,.LM36-.LFBB9
.LM36:
	b.andi  	r7,r6,524288
	b.beqi  	r7,0,.L23
	.stabn	68,0,110,.LM37-.LFBB9
.LM37:
	b.jal  	_wdt_interrupt_handler
	.stabn	68,0,113,.LM38-.LFBB9
.LM38:
	b.addi 	r6,r0,18434	  # movsi imm I
	bw.lwz   	r7,(_int_flag)(r0)	    # movsi load
	b.andi  	r7,r7,-524289
	l.mtspr r6,r7,0
	b.j    	.L20
.L23:
	.stabn	68,0,114,.LM39-.LFBB9
.LM39:
	b.andi  	r7,r6,256
	b.beqi  	r7,0,.L25
	.stabn	68,0,116,.LM40-.LFBB9
.LM40:
	b.jal  	_usb_interrupt_handler
	.stabn	68,0,118,.LM41-.LFBB9
.LM41:
	b.addi 	r6,r0,18434	  # movsi imm I
	bw.lwz   	r7,(_int_flag)(r0)	    # movsi load
	b.andi  	r7,r7,-257
	l.mtspr r6,r7,0
	b.j    	.L20
.L25:
	.stabn	68,0,120,.LM42-.LFBB9
.LM42:
	b.ori  	r3,r0,.LC0	  # movsi imm i
	b.jal  	_uart_print
	.stabn	68,0,122,.LM43-.LFBB9
.LM43:
	b.addi 	r6,r0,18434	  # movsi imm I
	b.movi 	r7,0	     # movsi imm P
	l.mtspr r6,r7,0
.L20:
	.stabn	68,0,125,.LM44-.LFBB9
.LM44:
	l.nop   0
	.stabn	68,0,126,.LM45-.LFBB9
.LM45:
	l.nop   0
	.stabn	68,0,127,.LM46-.LFBB9
.LM46:
	l.nop   0
	.stabn	68,0,128,.LM47-.LFBB9
.LM47:
	l.nop   0
	.stabn	68,0,129,.LM48-.LFBB9
.LM48:
	l.nop   0
	.stabn	68,0,130,.LM49-.LFBB9
.LM49:
	l.nop   0
	.stabn	68,0,131,.LM50-.LFBB9
.LM50:
	l.nop   0
	.stabn	68,0,132,.LM51-.LFBB9
.LM51:
	l.nop   0
	.stabn	68,0,133,.LM52-.LFBB9
.LM52:
	l.nop   0
	.stabn	68,0,135,.LM53-.LFBB9
.LM53:
	b.reti  	1,0
	.size	_IntHandler, .-_IntHandler
	.stabs	"val:r(0,4)",64,0,97,6
	.stabn	192,0,0,.LBB10-.LFBB9
	.stabn	224,0,0,.LBE10-.LFBB9
.Lscope9:
	.stabs	"",36,0,0,.Lscope9-.LFBB9
	.stabd	78,0,0
	.global _int_flag
.section .bss
	.align 4
	.type	_int_flag, @object
	.size	_int_flag, 4
_int_flag:
	.zero	4
	.comm	_pEventExternalTaskDone,4,4
	.stabs	"pEventExternalTaskDone:G(3,14)",32,0,15,0
	.stabs	"int_flag:G(4,6)",32,0,11,0
.section .internalrom, "ax"
	.stabs	"",100,0,0,.Letext0
.Letext0:
	.ident	"GCC: (GNU) 4.2.1"
