#ifndef _MAP_H_
#define _MAP_H_

#include "map.h" //jykim_20080715_HIF_CONV++

#define openrisc

#ifdef openrisc
//#define ISP_HIF_BASE	 	(0xD0061000)  //jykim_20080715_HIF_CONV--
#define ISP_HIF_BASE	 	(HIF_BASE_ADDR)   //jykim_20080715_HIF_CONV++
#else
#define ISP_HIF_BASE	 	(0xE000)
#endif 

#ifdef openrisc
//#define H264_HIF_BASE	(0xD0061060) //jykim_20080715_HIF_CONV--
#define H264_HIF_BASE	(HIF_BASE_ADDR + 0x00000060) //jykim_20080715_HIF_CONV++
#else
#define H264_HIF_BASE	(0xE400)
#endif

#ifdef openrisc
#define REG_INTERVAL		(0x4)
#else
#define REG_INTERVAL		(0x1)
#endif

#ifdef openrisc
#define ADDRESSING		(volatile int *)
#else
#define ADDRESSING			
#endif
// {{{
#define HIF_REG0_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 0)
#define HIF_REG1_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 1)
#define HIF_REG2_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 2)
#define HIF_REG3_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 3)
#define HIF_REG4_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 4)
#define HIF_REG5_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 5)
#define HIF_REG6_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 6)
#define HIF_REG7_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 7)
#define HIF_REG8_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 8)
#define HIF_REG9_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 9)
#define HIF_REG10_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 10)
#define HIF_REG11_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 11)
#define HIF_REG12_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 12)
#define HIF_REG13_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 13)
#define HIF_REG14_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 14)
#define HIF_REG15_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 15)
#define HIF_REG16_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 16)
#define HIF_REG17_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 17)
#define HIF_REG18_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 18)
#define HIF_REG19_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 19)
#define HIF_REG20_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 20)
#define HIF_REG21_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 21)
#define HIF_REG22_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 22)
#define HIF_REG23_ADDR	(ISP_HIF_BASE + REG_INTERVAL * 23)

#define HIF_REG24_ADDR	(H264_HIF_BASE + REG_INTERVAL * 0)
#define HIF_REG25_ADDR	(H264_HIF_BASE + REG_INTERVAL * 1)
#define HIF_REG26_ADDR	(H264_HIF_BASE + REG_INTERVAL * 2)
#define HIF_REG27_ADDR	(H264_HIF_BASE + REG_INTERVAL * 3)
#define HIF_REG28_ADDR	(H264_HIF_BASE + REG_INTERVAL * 4)
#define HIF_REG29_ADDR	(H264_HIF_BASE + REG_INTERVAL * 5)
#define HIF_REG30_ADDR	(H264_HIF_BASE + REG_INTERVAL * 6)
#define HIF_REG31_ADDR	(H264_HIF_BASE + REG_INTERVAL * 7)
#define HIF_REG32_ADDR	(H264_HIF_BASE + REG_INTERVAL * 8)
#define HIF_REG33_ADDR	(H264_HIF_BASE + REG_INTERVAL * 9)
#define HIF_REG34_ADDR	(H264_HIF_BASE + REG_INTERVAL * 10)
#define HIF_REG35_ADDR	(H264_HIF_BASE + REG_INTERVAL * 11)
#define HIF_REG36_ADDR	(H264_HIF_BASE + REG_INTERVAL * 12)
#define HIF_REG37_ADDR	(H264_HIF_BASE + REG_INTERVAL * 13)
#define HIF_REG38_ADDR	(H264_HIF_BASE + REG_INTERVAL * 14)
#define HIF_REG39_ADDR	(H264_HIF_BASE + REG_INTERVAL * 15)
#define HIF_REG40_ADDR	(H264_HIF_BASE + REG_INTERVAL * 16)
#define HIF_REG41_ADDR	(H264_HIF_BASE + REG_INTERVAL * 17)
#define HIF_REG42_ADDR	(H264_HIF_BASE + REG_INTERVAL * 18)
#define HIF_REG43_ADDR	(H264_HIF_BASE + REG_INTERVAL * 19)
#define HIF_REG44_ADDR	(H264_HIF_BASE + REG_INTERVAL * 20)
#define HIF_REG45_ADDR	(H264_HIF_BASE + REG_INTERVAL * 21)
#define HIF_REG46_ADDR	(H264_HIF_BASE + REG_INTERVAL * 22)
#define HIF_REG47_ADDR	(H264_HIF_BASE + REG_INTERVAL * 23)
#define HIF_REG48_ADDR	(H264_HIF_BASE + REG_INTERVAL * 24)
#define HIF_REG49_ADDR	(H264_HIF_BASE + REG_INTERVAL * 25)
#define HIF_REG50_ADDR	(H264_HIF_BASE + REG_INTERVAL * 26)
#define HIF_REG51_ADDR	(H264_HIF_BASE + REG_INTERVAL * 27)
#define HIF_REG52_ADDR	(H264_HIF_BASE + REG_INTERVAL * 28)
#define HIF_REG53_ADDR	(H264_HIF_BASE + REG_INTERVAL * 29)
#define HIF_REG54_ADDR	(H264_HIF_BASE + REG_INTERVAL * 30)
#define HIF_REG55_ADDR	(H264_HIF_BASE + REG_INTERVAL * 31)
#define HIF_REG56_ADDR	(H264_HIF_BASE + REG_INTERVAL * 32)
#define HIF_REG57_ADDR	(H264_HIF_BASE + REG_INTERVAL * 33)
#define HIF_REG58_ADDR	(H264_HIF_BASE + REG_INTERVAL * 34)
#define HIF_REG59_ADDR	(H264_HIF_BASE + REG_INTERVAL * 35)
#define HIF_REG60_ADDR	(H264_HIF_BASE + REG_INTERVAL * 36)
#define HIF_REG61_ADDR	(H264_HIF_BASE + REG_INTERVAL * 37)
#define HIF_REG62_ADDR	(H264_HIF_BASE + REG_INTERVAL * 38)
#define HIF_REG63_ADDR	(H264_HIF_BASE + REG_INTERVAL * 39)
#define HIF_REG64_ADDR	(H264_HIF_BASE + REG_INTERVAL * 40)
#define HIF_REG65_ADDR	(H264_HIF_BASE + REG_INTERVAL * 41)
#define HIF_REG66_ADDR	(H264_HIF_BASE + REG_INTERVAL * 42)
#define HIF_REG67_ADDR	(H264_HIF_BASE + REG_INTERVAL * 43)
#define HIF_REG68_ADDR	(H264_HIF_BASE + REG_INTERVAL * 44)
#define HIF_REG69_ADDR	(H264_HIF_BASE + REG_INTERVAL * 45)
#define HIF_REG70_ADDR	(H264_HIF_BASE + REG_INTERVAL * 46)
#define HIF_REG71_ADDR	(H264_HIF_BASE + REG_INTERVAL * 47)
#define HIF_REG72_ADDR	(H264_HIF_BASE + REG_INTERVAL * 48)
#define HIF_REG73_ADDR	(H264_HIF_BASE + REG_INTERVAL * 49)
#define HIF_REG74_ADDR	(H264_HIF_BASE + REG_INTERVAL * 50)
#define HIF_REG75_ADDR	(H264_HIF_BASE + REG_INTERVAL * 51)
#define HIF_REG76_ADDR	(H264_HIF_BASE + REG_INTERVAL * 52)
#define HIF_REG77_ADDR	(H264_HIF_BASE + REG_INTERVAL * 53)
#define HIF_REG78_ADDR	(H264_HIF_BASE + REG_INTERVAL * 54)
#define HIF_REG79_ADDR	(H264_HIF_BASE + REG_INTERVAL * 55)
#define HIF_REG80_ADDR	(H264_HIF_BASE + REG_INTERVAL * 56)
#define HIF_REG81_ADDR	(H264_HIF_BASE + REG_INTERVAL * 57)
#define HIF_REG82_ADDR	(H264_HIF_BASE + REG_INTERVAL * 58)
#define HIF_REG83_ADDR	(H264_HIF_BASE + REG_INTERVAL * 59)
#define HIF_REG84_ADDR	(H264_HIF_BASE + REG_INTERVAL * 60)
#define HIF_REG85_ADDR	(H264_HIF_BASE + REG_INTERVAL * 61)
#define HIF_REG86_ADDR	(H264_HIF_BASE + REG_INTERVAL * 62)
#define HIF_REG87_ADDR	(H264_HIF_BASE + REG_INTERVAL * 63)
#define HIF_REG88_ADDR	(H264_HIF_BASE + REG_INTERVAL * 64)
#define HIF_REG89_ADDR	(H264_HIF_BASE + REG_INTERVAL * 65)
#define HIF_REG90_ADDR	(H264_HIF_BASE + REG_INTERVAL * 66)
#define HIF_REG91_ADDR	(H264_HIF_BASE + REG_INTERVAL * 67)
#define HIF_REG92_ADDR	(H264_HIF_BASE + REG_INTERVAL * 68)
#define HIF_REG93_ADDR	(H264_HIF_BASE + REG_INTERVAL * 69)
#define HIF_REG94_ADDR	(H264_HIF_BASE + REG_INTERVAL * 70)
#define HIF_REG95_ADDR	(H264_HIF_BASE + REG_INTERVAL * 71)
#define HIF_REG96_ADDR	(H264_HIF_BASE + REG_INTERVAL * 72)
#define HIF_REG97_ADDR	(H264_HIF_BASE + REG_INTERVAL * 73)
#define HIF_REG98_ADDR	(H264_HIF_BASE + REG_INTERVAL * 74)
#define HIF_REG99_ADDR	(H264_HIF_BASE + REG_INTERVAL * 75)
#define HIF_REG100_ADDR	(H264_HIF_BASE + REG_INTERVAL * 76)
#define HIF_REG101_ADDR	(H264_HIF_BASE + REG_INTERVAL * 77)
#define HIF_REG102_ADDR	(H264_HIF_BASE + REG_INTERVAL * 78)
#define HIF_REG103_ADDR	(H264_HIF_BASE + REG_INTERVAL * 79)
#define HIF_REG104_ADDR	(H264_HIF_BASE + REG_INTERVAL * 80)
#define HIF_REG105_ADDR	(H264_HIF_BASE + REG_INTERVAL * 81)
#define HIF_REG106_ADDR	(H264_HIF_BASE + REG_INTERVAL * 82)
#define HIF_REG107_ADDR	(H264_HIF_BASE + REG_INTERVAL * 83)
#define HIF_REG108_ADDR	(H264_HIF_BASE + REG_INTERVAL * 84)
#define HIF_REG109_ADDR	(H264_HIF_BASE + REG_INTERVAL * 85)
#define HIF_REG110_ADDR	(H264_HIF_BASE + REG_INTERVAL * 86)
#define HIF_REG111_ADDR	(H264_HIF_BASE + REG_INTERVAL * 87)
#define HIF_REG112_ADDR	(H264_HIF_BASE + REG_INTERVAL * 88)
#define HIF_REG113_ADDR	(H264_HIF_BASE + REG_INTERVAL * 89)
#define HIF_REG114_ADDR	(H264_HIF_BASE + REG_INTERVAL * 90)
#define HIF_REG115_ADDR	(H264_HIF_BASE + REG_INTERVAL * 91)
#define HIF_REG116_ADDR	(H264_HIF_BASE + REG_INTERVAL * 92)
#define HIF_REG117_ADDR	(H264_HIF_BASE + REG_INTERVAL * 93)
#define HIF_REG118_ADDR	(H264_HIF_BASE + REG_INTERVAL * 94)
#define HIF_REG119_ADDR	(H264_HIF_BASE + REG_INTERVAL * 95)
#define HIF_REG120_ADDR	(H264_HIF_BASE + REG_INTERVAL * 96)
#define HIF_REG121_ADDR	(H264_HIF_BASE + REG_INTERVAL * 97)
#define HIF_REG122_ADDR	(H264_HIF_BASE + REG_INTERVAL * 98)
#define HIF_REG123_ADDR	(H264_HIF_BASE + REG_INTERVAL * 99)
#define HIF_REG124_ADDR	(H264_HIF_BASE + REG_INTERVAL * 100)
#define HIF_REG125_ADDR	(H264_HIF_BASE + REG_INTERVAL * 101)
#define HIF_REG126_ADDR	(H264_HIF_BASE + REG_INTERVAL * 102)
#define HIF_REG127_ADDR	(H264_HIF_BASE + REG_INTERVAL * 103)
#define HIF_REG128_ADDR	(H264_HIF_BASE + REG_INTERVAL * 104)
#define HIF_REG129_ADDR	(H264_HIF_BASE + REG_INTERVAL * 105)
#define HIF_REG130_ADDR	(H264_HIF_BASE + REG_INTERVAL * 106)
#define HIF_REG131_ADDR	(H264_HIF_BASE + REG_INTERVAL * 107)
#define HIF_REG132_ADDR	(H264_HIF_BASE + REG_INTERVAL * 108)
#define HIF_REG133_ADDR	(H264_HIF_BASE + REG_INTERVAL * 109)
#define HIF_REG134_ADDR	(H264_HIF_BASE + REG_INTERVAL * 110)
#define HIF_REG135_ADDR	(H264_HIF_BASE + REG_INTERVAL * 111)
#define HIF_REG136_ADDR	(H264_HIF_BASE + REG_INTERVAL * 112)
#define HIF_REG137_ADDR	(H264_HIF_BASE + REG_INTERVAL * 113)
#define HIF_REG138_ADDR	(H264_HIF_BASE + REG_INTERVAL * 114)
#define HIF_REG139_ADDR	(H264_HIF_BASE + REG_INTERVAL * 115)
#define HIF_REG140_ADDR	(H264_HIF_BASE + REG_INTERVAL * 116)
#define HIF_REG141_ADDR	(H264_HIF_BASE + REG_INTERVAL * 117)
#define HIF_REG142_ADDR	(H264_HIF_BASE + REG_INTERVAL * 118)
#define HIF_REG143_ADDR	(H264_HIF_BASE + REG_INTERVAL * 119)
#define HIF_REG144_ADDR	(H264_HIF_BASE + REG_INTERVAL * 120)
#define HIF_REG145_ADDR	(H264_HIF_BASE + REG_INTERVAL * 121)
#define HIF_REG146_ADDR	(H264_HIF_BASE + REG_INTERVAL * 122)
#define HIF_REG147_ADDR	(H264_HIF_BASE + REG_INTERVAL * 123)
#define HIF_REG148_ADDR	(H264_HIF_BASE + REG_INTERVAL * 124)
#define HIF_REG149_ADDR	(H264_HIF_BASE + REG_INTERVAL * 125)
#define HIF_REG150_ADDR	(H264_HIF_BASE + REG_INTERVAL * 126)
#define HIF_REG151_ADDR	(H264_HIF_BASE + REG_INTERVAL * 127)
#define HIF_REG152_ADDR	(H264_HIF_BASE + REG_INTERVAL * 128)
#define HIF_REG153_ADDR	(H264_HIF_BASE + REG_INTERVAL * 129)
#define HIF_REG154_ADDR	(H264_HIF_BASE + REG_INTERVAL * 130)
#define HIF_REG155_ADDR	(H264_HIF_BASE + REG_INTERVAL * 131)
#define HIF_REG156_ADDR	(H264_HIF_BASE + REG_INTERVAL * 132)
#define HIF_REG157_ADDR	(H264_HIF_BASE + REG_INTERVAL * 133)
#define HIF_REG158_ADDR	(H264_HIF_BASE + REG_INTERVAL * 134)
#define HIF_REG159_ADDR	(H264_HIF_BASE + REG_INTERVAL * 135)
#define HIF_REG160_ADDR	(H264_HIF_BASE + REG_INTERVAL * 136)
#define HIF_REG161_ADDR	(H264_HIF_BASE + REG_INTERVAL * 137)
#define HIF_REG162_ADDR	(H264_HIF_BASE + REG_INTERVAL * 138)
#define HIF_REG163_ADDR	(H264_HIF_BASE + REG_INTERVAL * 139)
#define HIF_REG164_ADDR	(H264_HIF_BASE + REG_INTERVAL * 140)
#define HIF_REG165_ADDR	(H264_HIF_BASE + REG_INTERVAL * 141)
#define HIF_REG166_ADDR	(H264_HIF_BASE + REG_INTERVAL * 142)
#define HIF_REG167_ADDR	(H264_HIF_BASE + REG_INTERVAL * 143)
#define HIF_REG168_ADDR	(H264_HIF_BASE + REG_INTERVAL * 144)
#define HIF_REG169_ADDR	(H264_HIF_BASE + REG_INTERVAL * 145)
#define HIF_REG170_ADDR	(H264_HIF_BASE + REG_INTERVAL * 146)
#define HIF_REG171_ADDR	(H264_HIF_BASE + REG_INTERVAL * 147)
#define HIF_REG172_ADDR	(H264_HIF_BASE + REG_INTERVAL * 148)
#define HIF_REG173_ADDR	(H264_HIF_BASE + REG_INTERVAL * 149)
#define HIF_REG174_ADDR	(H264_HIF_BASE + REG_INTERVAL * 150)
#define HIF_REG175_ADDR	(H264_HIF_BASE + REG_INTERVAL * 151)
#define HIF_REG176_ADDR	(H264_HIF_BASE + REG_INTERVAL * 152)
#define HIF_REG177_ADDR	(H264_HIF_BASE + REG_INTERVAL * 153)
#define HIF_REG178_ADDR	(H264_HIF_BASE + REG_INTERVAL * 154)
#define HIF_REG179_ADDR	(H264_HIF_BASE + REG_INTERVAL * 155)
#define HIF_REG180_ADDR	(H264_HIF_BASE + REG_INTERVAL * 156)
#define HIF_REG181_ADDR	(H264_HIF_BASE + REG_INTERVAL * 157)
#define HIF_REG182_ADDR	(H264_HIF_BASE + REG_INTERVAL * 158)
#define HIF_REG183_ADDR	(H264_HIF_BASE + REG_INTERVAL * 159)
#define HIF_REG184_ADDR	(H264_HIF_BASE + REG_INTERVAL * 160)
#define HIF_REG185_ADDR	(H264_HIF_BASE + REG_INTERVAL * 161)
#define HIF_REG186_ADDR	(H264_HIF_BASE + REG_INTERVAL * 162)
#define HIF_REG187_ADDR	(H264_HIF_BASE + REG_INTERVAL * 163)
#define HIF_REG188_ADDR	(H264_HIF_BASE + REG_INTERVAL * 164)
#define HIF_REG189_ADDR	(H264_HIF_BASE + REG_INTERVAL * 165)
#define HIF_REG190_ADDR	(H264_HIF_BASE + REG_INTERVAL * 166)
#define HIF_REG191_ADDR	(H264_HIF_BASE + REG_INTERVAL * 167)
#define HIF_REG192_ADDR	(H264_HIF_BASE + REG_INTERVAL * 168)
#define HIF_REG193_ADDR	(H264_HIF_BASE + REG_INTERVAL * 169)
#define HIF_REG194_ADDR	(H264_HIF_BASE + REG_INTERVAL * 170)
#define HIF_REG195_ADDR	(H264_HIF_BASE + REG_INTERVAL * 171)
#define HIF_REG196_ADDR	(H264_HIF_BASE + REG_INTERVAL * 172)
#define HIF_REG197_ADDR	(H264_HIF_BASE + REG_INTERVAL * 173)
#define HIF_REG198_ADDR	(H264_HIF_BASE + REG_INTERVAL * 174)
#define HIF_REG199_ADDR	(H264_HIF_BASE + REG_INTERVAL * 175)

#define HIF_REG0        ( ADDRESSING HIF_REG0_ADDR)        		 
#define HIF_REG1        ( ADDRESSING HIF_REG1_ADDR) 
#define HIF_REG2        ( ADDRESSING HIF_REG2_ADDR) 
#define HIF_REG3        ( ADDRESSING HIF_REG3_ADDR) 
#define HIF_REG4        ( ADDRESSING HIF_REG4_ADDR) 
#define HIF_REG5        ( ADDRESSING HIF_REG5_ADDR) 
#define HIF_REG6        ( ADDRESSING HIF_REG6_ADDR) 
#define HIF_REG7        ( ADDRESSING HIF_REG7_ADDR) 
#define HIF_REG8        ( ADDRESSING HIF_REG8_ADDR) 
#define HIF_REG9        ( ADDRESSING HIF_REG9_ADDR) 
#define HIF_REG10       ( ADDRESSING HIF_REG10_ADDR) 
#define HIF_REG11       ( ADDRESSING HIF_REG11_ADDR)
#define HIF_REG12       ( ADDRESSING HIF_REG12_ADDR)
#define HIF_REG13       ( ADDRESSING HIF_REG13_ADDR)
#define HIF_REG14       ( ADDRESSING HIF_REG14_ADDR)
#define HIF_REG15       ( ADDRESSING HIF_REG15_ADDR)
#define HIF_REG16       ( ADDRESSING HIF_REG16_ADDR)
#define HIF_REG17       ( ADDRESSING HIF_REG17_ADDR)
#define HIF_REG18       ( ADDRESSING HIF_REG18_ADDR)
#define HIF_REG19       ( ADDRESSING HIF_REG19_ADDR)
#define HIF_REG20       ( ADDRESSING HIF_REG20_ADDR)
#define HIF_REG21       ( ADDRESSING HIF_REG21_ADDR)
#define HIF_REG22       ( ADDRESSING HIF_REG22_ADDR)
#define HIF_REG23       ( ADDRESSING HIF_REG23_ADDR)

#define HIF_REG24       ( ADDRESSING HIF_REG24_ADDR)
#define HIF_REG25       ( ADDRESSING HIF_REG25_ADDR)
#define HIF_REG26       ( ADDRESSING HIF_REG26_ADDR)
#define HIF_REG27       ( ADDRESSING HIF_REG27_ADDR)
#define HIF_REG28       ( ADDRESSING HIF_REG28_ADDR)
#define HIF_REG29       ( ADDRESSING HIF_REG29_ADDR)
#define HIF_REG30       ( ADDRESSING HIF_REG30_ADDR)
#define HIF_REG31       ( ADDRESSING HIF_REG31_ADDR)
#define HIF_REG32       ( ADDRESSING HIF_REG32_ADDR)
#define HIF_REG33       ( ADDRESSING HIF_REG33_ADDR)
#define HIF_REG34       ( ADDRESSING HIF_REG34_ADDR)
#define HIF_REG35       ( ADDRESSING HIF_REG35_ADDR)
#define HIF_REG36       ( ADDRESSING HIF_REG36_ADDR)
#define HIF_REG37       ( ADDRESSING HIF_REG37_ADDR)
#define HIF_REG38       ( ADDRESSING HIF_REG38_ADDR)
#define HIF_REG39       ( ADDRESSING HIF_REG39_ADDR)
#define HIF_REG40       ( ADDRESSING HIF_REG40_ADDR)
#define HIF_REG41       ( ADDRESSING HIF_REG41_ADDR)
#define HIF_REG42       ( ADDRESSING HIF_REG42_ADDR)
#define HIF_REG43       ( ADDRESSING HIF_REG43_ADDR)
#define HIF_REG44       ( ADDRESSING HIF_REG44_ADDR)
#define HIF_REG45       ( ADDRESSING HIF_REG45_ADDR)
#define HIF_REG46       ( ADDRESSING HIF_REG46_ADDR)
#define HIF_REG47       ( ADDRESSING HIF_REG47_ADDR)
#define HIF_REG48       ( ADDRESSING HIF_REG48_ADDR)
#define HIF_REG49       ( ADDRESSING HIF_REG49_ADDR)
#define HIF_REG50       ( ADDRESSING HIF_REG50_ADDR)
#define HIF_REG51       ( ADDRESSING HIF_REG51_ADDR)
#define HIF_REG52       ( ADDRESSING HIF_REG52_ADDR)
#define HIF_REG53       ( ADDRESSING HIF_REG53_ADDR)
#define HIF_REG54       ( ADDRESSING HIF_REG54_ADDR)
#define HIF_REG55       ( ADDRESSING HIF_REG55_ADDR)
#define HIF_REG56       ( ADDRESSING HIF_REG56_ADDR)
#define HIF_REG57       ( ADDRESSING HIF_REG57_ADDR)
#define HIF_REG58     	( ADDRESSING HIF_REG58_ADDR)
#define HIF_REG59     	( ADDRESSING HIF_REG59_ADDR)
#define HIF_REG60     	( ADDRESSING HIF_REG60_ADDR)
#define HIF_REG61     	( ADDRESSING HIF_REG61_ADDR)
#define HIF_REG62     	( ADDRESSING HIF_REG62_ADDR)
#define HIF_REG63     	( ADDRESSING HIF_REG63_ADDR)
#define HIF_REG64     	( ADDRESSING HIF_REG64_ADDR)
#define HIF_REG65     	( ADDRESSING HIF_REG65_ADDR)
#define HIF_REG66     	( ADDRESSING HIF_REG66_ADDR)
#define HIF_REG67     	( ADDRESSING HIF_REG67_ADDR)
#define HIF_REG68     	( ADDRESSING HIF_REG68_ADDR)
#define HIF_REG69     	( ADDRESSING HIF_REG69_ADDR)
#define HIF_REG70     	( ADDRESSING HIF_REG70_ADDR)
#define HIF_REG71     	( ADDRESSING HIF_REG71_ADDR)
#define HIF_REG72     	( ADDRESSING HIF_REG72_ADDR)
#define HIF_REG73     	( ADDRESSING HIF_REG73_ADDR)
#define HIF_REG74     	( ADDRESSING HIF_REG74_ADDR)
#define HIF_REG75     	( ADDRESSING HIF_REG75_ADDR)
#define HIF_REG76     	( ADDRESSING HIF_REG76_ADDR)
#define HIF_REG77     	( ADDRESSING HIF_REG77_ADDR)
#define HIF_REG78     	( ADDRESSING HIF_REG78_ADDR)
#define HIF_REG79     	( ADDRESSING HIF_REG79_ADDR)
#define HIF_REG80     	( ADDRESSING HIF_REG80_ADDR)
#define HIF_REG81     	( ADDRESSING HIF_REG81_ADDR)
#define HIF_REG82     	( ADDRESSING HIF_REG82_ADDR)
#define HIF_REG83     	( ADDRESSING HIF_REG83_ADDR)
#define HIF_REG84     	( ADDRESSING HIF_REG84_ADDR)
#define HIF_REG85     	( ADDRESSING HIF_REG85_ADDR)
#define HIF_REG86     	( ADDRESSING HIF_REG86_ADDR)
#define HIF_REG87     	( ADDRESSING HIF_REG87_ADDR)
#define HIF_REG88     	( ADDRESSING HIF_REG88_ADDR)
#define HIF_REG89     	( ADDRESSING HIF_REG89_ADDR)
#define HIF_REG90     	( ADDRESSING HIF_REG90_ADDR)
#define HIF_REG91     	( ADDRESSING HIF_REG91_ADDR)
#define HIF_REG92     	( ADDRESSING HIF_REG92_ADDR)
#define HIF_REG93     	( ADDRESSING HIF_REG93_ADDR)
#define HIF_REG94     	( ADDRESSING HIF_REG94_ADDR)
#define HIF_REG95     	( ADDRESSING HIF_REG95_ADDR)
#define HIF_REG96     	( ADDRESSING HIF_REG96_ADDR)
#define HIF_REG97     	( ADDRESSING HIF_REG97_ADDR)
#define HIF_REG98     	( ADDRESSING HIF_REG98_ADDR)
#define HIF_REG99     	( ADDRESSING HIF_REG99_ADDR)
#define HIF_REG100   	( ADDRESSING HIF_REG100_ADDR)
#define HIF_REG101   	( ADDRESSING HIF_REG101_ADDR)
#define HIF_REG102   	( ADDRESSING HIF_REG102_ADDR)
#define HIF_REG103   	( ADDRESSING HIF_REG103_ADDR)
#define HIF_REG104   	( ADDRESSING HIF_REG104_ADDR)
#define HIF_REG105   	( ADDRESSING HIF_REG105_ADDR)
#define HIF_REG106   	( ADDRESSING HIF_REG106_ADDR)
#define HIF_REG107   	( ADDRESSING HIF_REG107_ADDR)
#define HIF_REG108   	( ADDRESSING HIF_REG108_ADDR)
#define HIF_REG109   	( ADDRESSING HIF_REG109_ADDR)
#define HIF_REG110   	( ADDRESSING HIF_REG110_ADDR)
#define HIF_REG111   	( ADDRESSING HIF_REG111_ADDR)
#define HIF_REG112   	( ADDRESSING HIF_REG112_ADDR)
#define HIF_REG113   	( ADDRESSING HIF_REG113_ADDR)
#define HIF_REG114   	( ADDRESSING HIF_REG114_ADDR)
#define HIF_REG115   	( ADDRESSING HIF_REG115_ADDR)
#define HIF_REG116   	( ADDRESSING HIF_REG116_ADDR)
#define HIF_REG117   	( ADDRESSING HIF_REG117_ADDR)
#define HIF_REG118   	( ADDRESSING HIF_REG118_ADDR)
#define HIF_REG119   	( ADDRESSING HIF_REG119_ADDR)
#define HIF_REG120   	( ADDRESSING HIF_REG120_ADDR)
#define HIF_REG121   	( ADDRESSING HIF_REG121_ADDR)
#define HIF_REG122   	( ADDRESSING HIF_REG122_ADDR)
#define HIF_REG123   	( ADDRESSING HIF_REG123_ADDR)
#define HIF_REG124   	( ADDRESSING HIF_REG124_ADDR)
#define HIF_REG125   	( ADDRESSING HIF_REG125_ADDR)
#define HIF_REG126   	( ADDRESSING HIF_REG126_ADDR)
#define HIF_REG127   	( ADDRESSING HIF_REG127_ADDR)
#define HIF_REG128      ( ADDRESSING HIF_REG128_ADDR)
#define HIF_REG129      ( ADDRESSING HIF_REG129_ADDR)
#define HIF_REG130      ( ADDRESSING HIF_REG130_ADDR)
#define HIF_REG131      ( ADDRESSING HIF_REG131_ADDR)
#define HIF_REG132      ( ADDRESSING HIF_REG132_ADDR)
#define HIF_REG133      ( ADDRESSING HIF_REG133_ADDR)
#define HIF_REG134      ( ADDRESSING HIF_REG134_ADDR)
#define HIF_REG135      ( ADDRESSING HIF_REG135_ADDR)
#define HIF_REG136      ( ADDRESSING HIF_REG136_ADDR)
#define HIF_REG137      ( ADDRESSING HIF_REG137_ADDR)
#define HIF_REG138      ( ADDRESSING HIF_REG138_ADDR)
#define HIF_REG139      ( ADDRESSING HIF_REG139_ADDR)
#define HIF_REG140      ( ADDRESSING HIF_REG140_ADDR)
#define HIF_REG141      ( ADDRESSING HIF_REG141_ADDR)
#define HIF_REG142      ( ADDRESSING HIF_REG142_ADDR)
#define HIF_REG143      ( ADDRESSING HIF_REG143_ADDR)
#define HIF_REG144      ( ADDRESSING HIF_REG144_ADDR)
#define HIF_REG145      ( ADDRESSING HIF_REG145_ADDR)
#define HIF_REG146      ( ADDRESSING HIF_REG146_ADDR)
#define HIF_REG147      ( ADDRESSING HIF_REG147_ADDR)
#define HIF_REG148      ( ADDRESSING HIF_REG148_ADDR)
#define HIF_REG149      ( ADDRESSING HIF_REG149_ADDR)
#define HIF_REG150      ( ADDRESSING HIF_REG150_ADDR)
#define HIF_REG151      ( ADDRESSING HIF_REG151_ADDR)
#define HIF_REG152      ( ADDRESSING HIF_REG152_ADDR)
#define HIF_REG153      ( ADDRESSING HIF_REG153_ADDR)
#define HIF_REG154      ( ADDRESSING HIF_REG154_ADDR)
#define HIF_REG155      ( ADDRESSING HIF_REG155_ADDR)
#define HIF_REG156      ( ADDRESSING HIF_REG156_ADDR)
#define HIF_REG157      ( ADDRESSING HIF_REG157_ADDR)
#define HIF_REG158     	( ADDRESSING HIF_REG158_ADDR)
#define HIF_REG159     	( ADDRESSING HIF_REG159_ADDR)
#define HIF_REG160     	( ADDRESSING HIF_REG160_ADDR)
#define HIF_REG161     	( ADDRESSING HIF_REG161_ADDR)
#define HIF_REG162     	( ADDRESSING HIF_REG162_ADDR)
#define HIF_REG163     	( ADDRESSING HIF_REG163_ADDR)
#define HIF_REG164     	( ADDRESSING HIF_REG164_ADDR)
#define HIF_REG165     	( ADDRESSING HIF_REG165_ADDR)
#define HIF_REG166     	( ADDRESSING HIF_REG166_ADDR)
#define HIF_REG167     	( ADDRESSING HIF_REG167_ADDR)
#define HIF_REG168     	( ADDRESSING HIF_REG168_ADDR)
#define HIF_REG169     	( ADDRESSING HIF_REG169_ADDR)
#define HIF_REG170     	( ADDRESSING HIF_REG170_ADDR)
#define HIF_REG171     	( ADDRESSING HIF_REG171_ADDR)
#define HIF_REG172     	( ADDRESSING HIF_REG172_ADDR)
#define HIF_REG173     	( ADDRESSING HIF_REG173_ADDR)
#define HIF_REG174     	( ADDRESSING HIF_REG174_ADDR)
#define HIF_REG175     	( ADDRESSING HIF_REG175_ADDR)
#define HIF_REG176     	( ADDRESSING HIF_REG176_ADDR)
#define HIF_REG177     	( ADDRESSING HIF_REG177_ADDR)
#define HIF_REG178     	( ADDRESSING HIF_REG178_ADDR)
#define HIF_REG179     	( ADDRESSING HIF_REG179_ADDR)
#define HIF_REG180     	( ADDRESSING HIF_REG180_ADDR)
#define HIF_REG181     	( ADDRESSING HIF_REG181_ADDR)
#define HIF_REG182     	( ADDRESSING HIF_REG182_ADDR)
#define HIF_REG183     	( ADDRESSING HIF_REG183_ADDR)
#define HIF_REG184     	( ADDRESSING HIF_REG184_ADDR)
#define HIF_REG185     	( ADDRESSING HIF_REG185_ADDR)
#define HIF_REG186     	( ADDRESSING HIF_REG186_ADDR)
#define HIF_REG187     	( ADDRESSING HIF_REG187_ADDR)
#define HIF_REG188     	( ADDRESSING HIF_REG188_ADDR)
#define HIF_REG189     	( ADDRESSING HIF_REG189_ADDR)
#define HIF_REG190     	( ADDRESSING HIF_REG190_ADDR)
#define HIF_REG191     	( ADDRESSING HIF_REG191_ADDR)
#define HIF_REG192     	( ADDRESSING HIF_REG192_ADDR)
#define HIF_REG193     	( ADDRESSING HIF_REG193_ADDR)
#define HIF_REG194     	( ADDRESSING HIF_REG194_ADDR)
#define HIF_REG195     	( ADDRESSING HIF_REG195_ADDR)
#define HIF_REG196     	( ADDRESSING HIF_REG196_ADDR)
#define HIF_REG197     	( ADDRESSING HIF_REG197_ADDR)
#define HIF_REG198     	( ADDRESSING HIF_REG198_ADDR)
#define HIF_REG199     	( ADDRESSING HIF_REG199_ADDR)
// }}}

#define CHIP_I2C_ADDR				          	*HIF_REG0
//#define 							          	*HIF_REG1
#define SENSOR_OUT_W	 				        *HIF_REG2
#define SENSOR_OUT_H	 				        *HIF_REG3
#define IMAGE_OUT_W	 				          	*HIF_REG4
#define IMAGE_OUT_H	 				          	*HIF_REG5
#define H264_OUTPUT					          	*HIF_REG6
	#define H264_RESOLUTION			( H264_OUTPUT & 0x03 )
	#define H264_VGA				0
	#define H264_QVGA				1
	#define H264_QQVGA				2
	#define H264_HD					3
#define AIC_CONTROL 		 		          	*HIF_REG7
	#define AIC_CONTROL_FREQ		( AIC_CONTROL & 0x03 )
	#define AIC_FREQ_16KHZ			0
	#define AIC_FREQ_12KHZ			1
#define CONSTANT_QP_VALUE 	 		          	*HIF_REG8
#define	MAX_BIT_RATE_LOW 	 		          	*HIF_REG9
#define	MAX_BIT_RATE_HIGH	 			       	*HIF_REG10
	#define MAX_BIT_RATE_VALUE ( ( ( (MAX_BIT_RATE_LOW  << 0) & 0x000000ff ) \
		                            	|   ( (MAX_BIT_RATE_HIGH << 8) & 0x0000ff00 ) \
						                ) * 1024 )

#define FW_UPLOAD	 				          	*HIF_REG11
	#define FW_UPLOAD_DONE_BIT	 				    ( 1 << 0 )
	#define FW_UPLOAD_VALID_ERROR_BIT	 			( 1 << 1 )
#define VIDEO_PROP_SET0 			          	*HIF_REG12
#define VIDEO_PROP_SET1	 			          	*HIF_REG13
#define	VIDEO_PROP_SET2				          	*HIF_REG14
#define VIDEO_PROP_SET3 			          	*HIF_REG15
#define VIDEO_PROP_SET4				          	*HIF_REG16
	#define VIDEO_PROP_CONTRAST			((VIDEO_PROP_SET0 >> 0) & 0x0f)
	#define VIDEO_PROP_BRIGHTNESS		((VIDEO_PROP_SET0 >> 4) & 0x0f)
	#define VIDEO_PROP_SATURATION		((VIDEO_PROP_SET1 >> 0) & 0x0f)
	#define VIDEO_PROP_SHARPNESS		((VIDEO_PROP_SET1 >> 4) & 0x0f)
	#define VIDEO_PROP_HUE				((VIDEO_PROP_SET2 >> 0) & 0x0f)
	#define VIDEO_PROP_GAMMA			((VIDEO_PROP_SET2 >> 4) & 0x0f)
	#define VIDEO_PROP_WHITE_BALANCE	((VIDEO_PROP_SET3 >> 0) & 0x0f)
	#define VIDEO_PROP_EXPOSURE			((VIDEO_PROP_SET3 >> 4) & 0x0f)
	#define VIDEO_PROP_POWER_LINE_FREQ	((VIDEO_PROP_SET4 >> 0) & 0x0f)
#define JPEG_FPS		                       	*HIF_REG17
//#define 			                         	*HIF_REG18
//#define 			                         	*HIF_REG19
//#define 			                         	*HIF_REG20
//#define 					 					*HIF_REG21
//#define 										*HIF_REG22
#define HOST_RESET								*HIF_REG23
	#define CAM2_PWDN            (((HOST_RESET)>>4)&0x1)
	#define CAM2_SCALING         (((HOST_RESET)>>5)&0x1)
	#define CAM2_SCALING_EN      (((HOST_RESET)>>6)&0x1)
	#define DUAL_STREAM          (((HOST_RESET)>>7)&0x1)
#define QP_VALUE_I	 							*HIF_REG24
#define QP_VALUE_P	 							*HIF_REG25
#define INTRA_PERIOD	 						*HIF_REG26
//#define 										*HIF_REG27
//#define 						   				*HIF_REG28
//#define 										*HIF_REG29
//#define 										*HIF_REG30
#define ENABLE_FLAG	 							*HIF_REG31
	#define LOOP_FILTER_PARAMETERS_DISABLE_FLAG (( ENABLE_FLAG & 0x01 ) >> 0 )
	#define RATE_CONTROL_DISABLE_FLAG           (( ENABLE_FLAG & 0x02 ) >> 1 )
	#define DOUBLE_BUFFER_DISABLE_FLAG          (( ENABLE_FLAG & 0x04 ) >> 2 )
//#define 										*HIF_REG32
//#define 										*HIF_REG33
//#define 										*HIF_REG34
//#define 										*HIF_REG35
//#define 										*HIF_REG36
//#define 										*HIF_REG37
//#define 										*HIF_REG38
//#define 										*HIF_REG39
//#define 										*HIF_REG40
//#define 			  							*HIF_REG41
//#define 			  							*HIF_REG42
//#define 			  							*HIF_REG43
//#define 										*HIF_REG44
//#define 						 				*HIF_REG45
//#define 						 				*HIF_REG46
//#define 						 				*HIF_REG47
//#define 						 				*HIF_REG48
//#define  			                         	*HIF_REG49
#define JPEG_QUALITY_FACTOR                		*HIF_REG50
#define JPEG_WIDTH                         		*HIF_REG51
#define JPEG_HEIGHT                        		*HIF_REG52
#define OM_SELECT	 		       				*HIF_REG53 
	#define OM_SELECT_DIAGNOSIS_ENABLE     (( OM_SELECT  & 0x01 ) >> 0 )
	#define OM_SELECT_SRAM_SEL_EN          (( OM_SELECT  & 0x02 ) >> 1 )
	#define OM_SELECT_I2C_ON_OFF           (( OM_SELECT  & 0x04 ) >> 2 )
	#define OM_SELECT_EXTERN_CODE_MEM_TYPE (( OM_SELECT  & 0x08 ) >> 3 )
	#define OM_SELECT_I2C_M_SELECT_BIT     ( 1 << 4 )
	#define OM_SELECT_UPHY_IN_REG_BIT      ( 1 << 5 )
	#define OM_SELECT_DVP_NOT_SELECT_BIT   ( 1 << 6 )
#define OPERATION_DEFINE1        				*HIF_REG54 
	#define H264E_SXGA_TO_VGA_HIF    (( OPERATION_DEFINE1  & 0x01 ) >> 0 )
	#define SLICE_MODE_HIF           (( OPERATION_DEFINE1  & 0x02 ) >> 1 )
	#define USE_ADF_HIF              (( OPERATION_DEFINE1  & 0x04 ) >> 2 )
	#define H264E_MAX_VGA_HIF        (( OPERATION_DEFINE1  & 0x08 ) >> 3 )
	#define SPEED_CONTROL_HIF        (( OPERATION_DEFINE1  & 0x10 ) >> 4 )
	#define OFFSET_CONTROL_HIF       (( OPERATION_DEFINE1  & 0x20 ) >> 5 )
	#define NO_FASTME_HIF            (( OPERATION_DEFINE1  & 0x40 ) >> 6 )
	#define ME_EARLY_TERMINATION_HIF (( OPERATION_DEFINE1  & 0x80 ) >> 7 )
#define OPERATION_DEFINE2        				*HIF_REG55 
	#define H264E_SAFE_MODE_HIF               (( OPERATION_DEFINE2  & 0x10 ) >> 4 )
	#define FRAME_RATE_CONTROL_ENABLE_FLAG    (( OPERATION_DEFINE2  & 0x20 ) >> 5 )
#define FRAME_SKIP               				*HIF_REG56
	#define HIF_NAL_SLICE_MODE	((*HIF_REG56 & 0x80) >> 7)
	#define NAL_SIZE 		    ((*HIF_REG56 & 0x7f) << 4)	
#define SLICE_ARGUMENT           				*HIF_REG57
#define LF_ALPHA_CO_OFFSET     					*HIF_REG58
#define LF_BETA_OFFSET          				*HIF_REG59
#define I2S_CTRL_PARAM_LOW          			*HIF_REG60
#define I2S_CTRL_PARAM_HIGH         			*HIF_REG61
	#define RX_STEREO			( I2S_CTRL_PARAM_LOW & 0x00000003 )
	#define TX_STEREO			( ( I2S_CTRL_PARAM_LOW >> 2 ) & 0x00000003 )
	#define DATA_FORMAT			( ( I2S_CTRL_PARAM_LOW >> 4 ) & 0x00000007 )
	#define BIT_ORDER_CHANGE 	( ( I2S_CTRL_PARAM_LOW >> 7 ) & 0x00000001 )
	#define RX_IRQ_SIZE			( I2S_CTRL_PARAM_HIGH & 0x0000000f )
	#define TX_IRQ_SIZE			( ( I2S_CTRL_PARAM_HIGH >> 4 ) & 0x0000000f )
#define OPERATION_DEFINE3        				*HIF_REG62
	#define KEYFRAME_REQUEST    	(( OPERATION_DEFINE3  & 0x01 ) >> 0 )
	#define KEYFRAME_REQUEST_BIT    ( 1 << 0 )
#define AUDIO_GAIN								*HIF_REG63
#define ZOOM_LEVEL								*HIF_REG64
#define AVATA_MODE								*HIF_REG65
#define RATE_CONTROL_BIT_RATE_LOW          		*HIF_REG66
#define RATE_CONTROL_BIT_RATE_HIGH         		*HIF_REG67
	#define RATE_CONTROL_BIT_RATE_VALUE ( ( ( (RATE_CONTROL_BIT_RATE_LOW  << 0) & 0x000000ff ) \
		                              	|   ( (RATE_CONTROL_BIT_RATE_HIGH << 8) & 0x0000ff00 ) \
						                ) * 1024 )
#define RATE_CONTROL_FRAME_RATE            		*HIF_REG68
#define RATE_CONTROL_SEINITIAL_QP          		*HIF_REG69
	#define RATE_CONTROL_SEINITIAL_QP_VALUE  ( RATE_CONTROL_SEINITIAL_QP & 0x1f )
	#define OSB_FIFO_RATE_IDX  ( 1 << ( (RATE_CONTROL_SEINITIAL_QP & 0xe0) >> 5 ) )
#define SPEED_CONTROL_MB_CYCLE_LOW         		*HIF_REG70
#define SPEED_CONTROL_MB_CYCLE_HIGH        		*HIF_REG71
	#define SPEED_CONTROL_MB_CYCLE_VALUE  ( ( (SPEED_CONTROL_MB_CYCLE_LOW << 0) & 0x000000ff ) \
			                                | ( (SPEED_CONTROL_MB_CYCLE_HIGH << 8) & 0x0000ff00 ) )
//#define 						  				*HIF_REG72 //default : 0x1C 
//#define 						  				*HIF_REG73 //default : 0x04  //1052
#define SENSOR2_OUT_W	 						*HIF_REG74 
#define SENSOR2_OUT_H	 						*HIF_REG75 
#define IMAGE2_OUT_W	 						*HIF_REG76 
#define IMAGE2_OUT_H	 						*HIF_REG77 
//#define 					    				*HIF_REG78
//#define 					    				*HIF_REG79
//#define 					    				*HIF_REG80
//#define 					    				*HIF_REG81
//#define 					    				*HIF_REG82
//#define 					    				*HIF_REG83
//#define 					    				*HIF_REG84
//#define 					    				*HIF_REG85
//#define 					    				*HIF_REG86
//#define 					    				*HIF_REG87
//#define 					    				*HIF_REG88
//#define 					    				*HIF_REG89
//#define 					    				*HIF_REG90
//#define 					    				*HIF_REG91
//#define 					    				*HIF_REG92
//#define 					    				*HIF_REG93
//#define 					    				*HIF_REG94
//#define 					    				*HIF_REG95
//#define 					    				*HIF_REG96
//#define 					    				*HIF_REG97
//#define 					    				*HIF_REG98
//#define 					    				*HIF_REG99
//#define 					    				*HIF_REG100
//#define 					    				*HIF_REG101
#define CHIP_STATUS              				*HIF_REG102
	#define CAM_NUM_SEL_JPEG  		(((CHIP_STATUS) >> 7)&0x1 )
	#define CAM_NUM_SEL_264   		(((CHIP_STATUS) >> 6)&0x1 )
	#define PARAM_SET_END           ( CHIP_STATUS & 0x01 )
	#define CHIP_READY              ( CHIP_STATUS & 0x02 )
	#define PARAM_SET_END_BIT       ( 1 << 0 )
	#define CHIP_READY_BIT          ( 1 << 1 )
	#define CAM2_CLK_DIV_VALUE 		( ( CHIP_STATUS & 0x3c ) >> 2 )
#define PLL_MODE								*HIF_REG103
	#define PLL_MODE_BYPASS			( PLL_MODE & 0x01 )
	#define DRAMC_CLK_DIV_VALUE		( ( PLL_MODE & 0xf0 ) >> 4 )
#define PLL_DIVIDER_LOW							*HIF_REG104
#define PLL_DIVIDER_HIGH						*HIF_REG105
	#define PLL_INPUT_DIV_VALUE		( PLL_DIVIDER_LOW & 0x3f )
	#define PLL_OUTPUT_DIV_VALUE	( ( PLL_DIVIDER_LOW & 0xc0 ) >> 6 )
	#define PLL_FEEDBACK_DIV_VALUE  ( PLL_DIVIDER_HIGH ) 
#define PLL_LOCKTIME_LOW						*HIF_REG106
#define PLL_LOCKTIME_HIGH						*HIF_REG107
	#define PLL_LOCKTIME_VALUE	    ( ( PLL_LOCKTIME_LOW & 0x000000ff ) \
			                        | ( (PLL_LOCKTIME_HIGH << 8 ) & 0x0000ff00) )
#define CLK_DIV_LOW								*HIF_REG108
#define CLK_DIV_HIGH							*HIF_REG109
	#define SYS_CLK_DIV_VALUE		( CLK_DIV_LOW & 0x0f )
	#define RISC_CLK_DIV_VALUE	 	( ( CLK_DIV_LOW & 0xf0 ) >> 4 )
	#define AMBA_CLK_DIV_VALUE		( CLK_DIV_HIGH & 0x0f )
	#define CAM_CLK_DIV_VALUE	 	( ( CLK_DIV_HIGH & 0xf0 ) >> 4 )
//#define 					     				*HIF_REG110
//#define 					     				*HIF_REG111
//#define 					     				*HIF_REG112
//#define 					     				*HIF_REG113
//#define 					     				*HIF_REG114
//#define 					     				*HIF_REG115
//#define 					     				*HIF_REG116
//#define 					     				*HIF_REG117
//#define 					     				*HIF_REG118
//#define 					     				*HIF_REG119
//#define 					     				*HIF_REG120
//#define 					     				*HIF_REG121
//#define 					     				*HIF_REG122
//#define 					     				*HIF_REG123
//#define 					     				*HIF_REG124
//#define 					      				*HIF_REG125
//#define 					    				*HIF_REG126
//#define 					     				*HIF_REG127
//#define 				        				*HIF_REG128
//#define	 				       				*HIF_REG129
//#define 					       				*HIF_REG130
//#define 					       				*HIF_REG131
#define PLL_INPUT_CLOCK_LOW						*HIF_REG132
#define PLL_INPUT_CLOCK_HIGH					*HIF_REG133
	#define PLL_INPUT_CLOCK_VALUE       ( ( ( (PLL_INPUT_CLOCK_LOW  << 0) & 0x000000ff ) \
		                              	|   ( (PLL_INPUT_CLOCK_HIGH << 8) & 0x0000ff00 ) \
						                ) * 1000 )
#define UART_BAUD_RATE							*HIF_REG134
	#define UART_BAUD_RATE_SEL			( UART_BAUD_RATE & 0x01 )
	#define UART_BAUD_RATE_SEL_DEFAULT		0
	#define UART_BAUD_RATE_SEL_HIF			1
	#define UART_BAUD_RATE_VALUE        ( ( UART_BAUD_RATE & 0x0e ) >> 1 )
	#define UART_BAUD_RATE_VALUE_4800			0
	#define UART_BAUD_RATE_VALUE_9600			1
	#define UART_BAUD_RATE_VALUE_14400			2
	#define UART_BAUD_RATE_VALUE_19200			3
	#define UART_BAUD_RATE_VALUE_38400			4
	#define UART_BAUD_RATE_VALUE_57600			5
	#define UART_BAUD_RATE_VALUE_115200			6
	#define UART_BAUD_RATE_VALUE_128000			7
#define SPI_M_CLK_DIVIDER_LOW					*HIF_REG135
#define SPI_M_CLK_DIVIDER_HIGH					*HIF_REG136
	#define SPI_M_CLK_DIVIDER_VALUE   	( ( SPI_M_CLK_DIVIDER_LOW & 0x000000ff ) \
			     	                    | ( (SPI_M_CLK_DIVIDER_HIGH << 8 ) & 0x0000ff00) )
#define I2C_M_PRESCALE_LOW					   	*HIF_REG138
#define I2C_M_PRESCALE_HIGH					   	*HIF_REG139
#define SDRAM_MODE_REG0 						*HIF_REG140
#define SDRAM_MODE_REG1 						*HIF_REG141
#define SDRAM_MODE_REG2 						*HIF_REG142
#define SDRAM_MODE_REG3 						*HIF_REG143
	#define SDRAM_MODE_REG_VALUE  	(  ( (SDRAM_MODE_REG0 << 0 ) & 0x000000ff ) \
			                        |  ( (SDRAM_MODE_REG1 << 8 ) & 0x0000ff00 ) \
			                        |  ( (SDRAM_MODE_REG2 << 16) & 0x00ff0000 ) \
			                        |  ( (SDRAM_MODE_REG3 << 24) & 0xff000000 ) )
	#define SDRAM_CL              	( ( SDRAM_MODE_REG_VALUE >>  0 ) & 0x0007 )
	#define SDRAM_TREF            	( ( SDRAM_MODE_REG_VALUE >>  3 ) & 0x0fff )
	#define SDRAM_TRFC            	( ( SDRAM_MODE_REG_VALUE >> 15 ) & 0x000f )
	#define SDRAM_TRP             	( ( SDRAM_MODE_REG_VALUE >> 19 ) & 0x0007 )
	#define SDRAM_TRAS            	( ( SDRAM_MODE_REG_VALUE >> 22 ) & 0x0007 )
	#define SDRAM_TRCD            	( ( SDRAM_MODE_REG_VALUE >> 25 ) & 0x0007 )
	#define SDRAM_SDRAMC_TRMODE   	( ( SDRAM_MODE_REG3 & 0x10 ) >> 4 )
	#define SDRAM_SDRAMC_CONFIG   	( ( SDRAM_MODE_REG3 & 0x80 ) >> 7 )


#define OM_SELECT2			       				*HIF_REG144 
	#define OM_SELECT2_CAM_SEL                  	(( OM_SELECT2  & 0x01 ) >> 0 )
	#define OM_SELECT2_PCI_SEL                  	(( OM_SELECT2  & 0x02 ) >> 1 )
	#define OM_SELECT2_GPIO_SEL                 	(( OM_SELECT2  & 0x04 ) >> 2 )
	#define OM_SELECT2_BOOT_MODE                	(( OM_SELECT2  & 0x18 ) >> 3 )
	#define OM_SELECT2_EXTERNAL_CODE_SOURCE     	(( OM_SELECT2  & 0x20 ) >> 5 )
	#define OM_SELECT2_DIAGNOSIS_PATTERN_ENABLE 	(( OM_SELECT2  & 0x40 ) >> 6 )

#define INTERRUPT_CONTROL_0	       				*HIF_REG145 
#define INTERRUPT_CONTROL_1	       				*HIF_REG146 
#define INTERRUPT_CONTROL_2	       				*HIF_REG147 
	#define INTERRUPT_CONTROL_VALUE (  ( (INTERRUPT_CONTROL_0 << 0 ) & 0x000000ff ) \
		                            |  ( (INTERRUPT_CONTROL_1 << 8 ) & 0x0000ff00 ) \
		                            |  ( (INTERRUPT_CONTROL_2 << 16) & 0x000f0000 ) )

	#define TIMER_INT_ENABLE		(( INTERRUPT_CONTROL_2  & 0x80 ) >> 7 ) 
	#define UNMASKED1_INT_BIT         ( 1 <<  0 ) 
	#define UNMASKED2_INT_BIT         ( 1 <<  1 )      
	#define AHB2APB_HIF_INT_BIT       ( 1 <<  2 )      
	#define ISP_INT_BIT               ( 1 <<  3 )
	#define SDIO0_WB_INT_BIT          ( 1 <<  4 )
	#define SDIO1_WB_INT_BIT          ( 1 <<  5 )
	#define USB_DEV_SUSP_O_BIT        ( 1 <<  6 )
	#define USB_DEV_INTB_O_BIT        ( 1 <<  7 )
	#define USB_DEV_INTA_O_BIT        ( 1 <<  8 )
	#define IIC_INT_BIT               ( 1 <<  9 )
	#define SPI_MASTER_INT_BIT        ( 1 << 10 )
	#define AHB2APB_GPIO_INT_BIT      ( 1 << 11 )
	#define I2S_RX_IRQ_BIT     		  ( 1 << 12 )
	#define I2S_TX_IRQ_BIT     		  ( 1 << 13 )
	#define I2S1_RX_IRQ_BIT    		  ( 1 << 14 )
	#define I2S1_TX_IRQ_BIT    		  ( 1 << 15 )
	#define PTC_WB_INT_BIT    		  ( 1 << 18 )
	#define WDT_WB_INT_BIT    		  ( 1 << 19 )

#define TIMER_INT_PERIOD_0	       				*HIF_REG148 
#define TIMER_INT_PERIOD_1	       				*HIF_REG149 
#define TIMER_INT_PERIOD_2	       				*HIF_REG150 
	#define TIMER_INT_PERIOD_VALUE	((((TIMER_INT_PERIOD_0<< 0)&0x000000ff)  \
			                        | ((TIMER_INT_PERIOD_1<< 8)&0x0000ff00)  \
			                        | ((TIMER_INT_PERIOD_2<<16)&0x00ff0000)) \
		 						 	<< 4 )	
//#define 										*HIF_REG152
#define EXTERNAL_PGM_SIZE_LOW					*HIF_REG153
#define EXTERNAL_PGM_SIZE_HIGH					*HIF_REG154
#define EXTERNAL_PGM_SIZE_VALUE 	((((EXTERNAL_PGM_SIZE_LOW << 0) & 0x000000ff ) \
		                            | ((EXTERNAL_PGM_SIZE_HIGH << 8) & 0x0000ff00 ) \
						            ) * 16 )
//#define 										*HIF_REG155
//#define 										*HIF_REG156
//#define 										*HIF_REG157
//#define 										*HIF_REG158
//#define 										*HIF_REG159
//#define 										*HIF_REG160
//#define 										*HIF_REG161
//#define 										*HIF_REG162
//#define 										*HIF_REG163
//#define 										*HIF_REG164
//#define 										*HIF_REG165
//#define 										*HIF_REG166
//#define 										*HIF_REG167
//#define 										*HIF_REG168
//#define 										*HIF_REG169
//#define 										*HIF_REG170
//#define 										*HIF_REG171
//#define 										*HIF_REG172
//#define 										*HIF_REG173
//#define 										*HIF_REG174
//#define 										*HIF_REG175
//#define 										*HIF_REG176
//#define 										*HIF_REG177
//#define 										*HIF_REG178
//#define 										*HIF_REG179
//#define 										*HIF_REG180
#define PERI_GATING_0	       					*HIF_REG181
#define PERI_GATING_1	       					*HIF_REG182
#define PERI_GATING_2	       					*HIF_REG183
#define PERI_GATING_3	       					*HIF_REG184
	#define PERI_GATING_VALUE      	(  ( (PERI_GATING_0 << 0 ) & 0x000000ff ) \
		                            |  ( (PERI_GATING_1 << 8 ) & 0x0000ff00 ) \
		                            |  ( (PERI_GATING_2 << 16) & 0x00ff0000 ) \
		                            |  ( (PERI_GATING_3 << 24) & 0xff000000 ) )
//#define 					   					*HIF_REG185
//#define 					   					*HIF_REG186
//#define 					   					*HIF_REG187
//#define 					   					*HIF_REG188
//#define 					   					*HIF_REG189
#define ME_FAST_FME_CONTROL_0	   				*HIF_REG190
#define ME_FAST_FME_CONTROL_1	   				*HIF_REG191
#define ME_FAST_FME_CONTROL_2	   				*HIF_REG192
#define ME_FAST_FME_CONTROL_3	   				*HIF_REG193
#define ME_FAST_FME_CONTROL_VALUE 	(((ME_FAST_FME_CONTROL_0 << 0 ) & 0x000000ff ) \
		                            |((ME_FAST_FME_CONTROL_1 << 8 ) & 0x0000ff00 ) \
		                            |((ME_FAST_FME_CONTROL_2 << 16) & 0x00ff0000 ) \
		                            |((ME_FAST_FME_CONTROL_3 << 24) & 0xff000000 ) )
#define AFIFO_ALMOST_FULL_SIZE  				*HIF_REG194
//#define 			    					   	*HIF_REG195 
#define PID_0                     				*HIF_REG196
#define PID_1                     				*HIF_REG197
#define PID_2                     				*HIF_REG198
#define PID_3                     				*HIF_REG199
	#define PID_VALUE 	(  ( (PID_0 << 0 ) & 0x000000ff ) \
		            	|  ( (PID_1 << 8 ) & 0x0000ff00 ) \
		            	|  ( (PID_2 << 16) & 0x00ff0000 ) \
		            	|  ( (PID_3 << 24) & 0xff000000 ) )

#endif



