	.file	"i2s.c"
	.stabs	"/home/hanguru/2011_project_original/lgdtv_vidan4110_fw_capp_project/software/vi_fw_project/",100,0,2,.Ltext0
	.stabs	"internal/i2s.c",100,0,2,.Ltext0
.section .internalrom, "ax"
.Ltext0:
	.stabs	"gcc2_compiled.",60,0,0,0
	.stabs	"int:t(0,1)=r(0,1);-2147483648;2147483647;",128,0,0,0
	.stabs	"char:t(0,2)=r(0,2);0;127;",128,0,0,0
	.stabs	"long int:t(0,3)=r(0,3);-2147483648;2147483647;",128,0,0,0
	.stabs	"unsigned int:t(0,4)=r(0,4);0;037777777777;",128,0,0,0
	.stabs	"long unsigned int:t(0,5)=r(0,5);0;037777777777;",128,0,0,0
	.stabs	"long long int:t(0,6)=@s64;r(0,6);01000000000000000000000;0777777777777777777777;",128,0,0,0
	.stabs	"long long unsigned int:t(0,7)=@s64;r(0,7);0;01777777777777777777777;",128,0,0,0
	.stabs	"short int:t(0,8)=@s16;r(0,8);-32768;32767;",128,0,0,0
	.stabs	"short unsigned int:t(0,9)=@s16;r(0,9);0;65535;",128,0,0,0
	.stabs	"signed char:t(0,10)=@s8;r(0,10);-128;127;",128,0,0,0
	.stabs	"unsigned char:t(0,11)=@s8;r(0,11);0;255;",128,0,0,0
	.stabs	"float:t(0,12)=r(0,1);4;0;",128,0,0,0
	.stabs	"double:t(0,13)=r(0,1);8;0;",128,0,0,0
	.stabs	"long double:t(0,14)=r(0,1);8;0;",128,0,0,0
	.stabs	"void:t(0,15)=(0,15)",128,0,0,0
	.stabs	"ucos/interrupt_handler.h",130,0,0,0
	.stabs	"ucos/task_manage.h",130,0,0,0
	.stabs	"ucos/ucos_ii.h",130,0,0,0
	.stabs	"ucos/os_cpu.h",130,0,0,0
	.stabs	"BOOLEAN:t(4,1)=(0,11)",128,0,9,0
	.stabs	"INT8U:t(4,2)=(0,11)",128,0,10,0
	.stabs	"INT8S:t(4,3)=(0,2)",128,0,11,0
	.stabs	"INT16U:t(4,4)=(0,9)",128,0,12,0
	.stabs	"INT16S:t(4,5)=(0,8)",128,0,13,0
	.stabs	"INT32U:t(4,6)=(0,5)",128,0,14,0
	.stabs	"INT32S:t(4,7)=(0,3)",128,0,15,0
	.stabs	"VBOOLEAN:t(4,8)=(4,9)=B(0,11)",128,0,16,0
	.stabs	"OS_STK:t(4,10)=(0,4)",128,0,17,0
	.stabs	"OS_CPU_SR:t(4,11)=(0,4)",128,0,18,0
	.stabn	162,0,0,0
	.stabs	"ucos/os_cfg.h",130,0,0,0
	.stabs	"OS_FLAGS:t(5,1)=(4,4)",128,0,112,0
	.stabn	162,0,0,0
	.stabs	"os_event:T(3,1)=s44OSEventType:(4,2),0,8;OSEventGrp:(4,2),8,8;OSEventCnt:(4,4),16,16;OSEventPtr:(3,2)=*(0,15),32,32;OSEventTbl:(3,3)=ar(3,4)=r(3,4);0;037777777777;;0;0;(4,2),64,8;OSEventName:(3,5)=ar(3,4);0;31;(0,2),72,256;;",128,0,0,0
	.stabs	"OS_EVENT:t(3,6)=(3,1)",128,0,257,0
	.stabs	"os_sem_data:T(3,7)=s4OSCnt:(4,4),0,16;OSEventTbl:(3,3),16,8;OSEventGrp:(4,2),24,8;;",128,0,0,0
	.stabs	"OS_SEM_DATA:t(3,8)=(3,7)",128,0,387,0
	.stabs	"os_stk_data:T(3,9)=s8OSFree:(4,6),0,32;OSUsed:(4,6),32,32;;",128,0,0,0
	.stabs	"OS_STK_DATA:t(3,10)=(3,9)",128,0,400,0
	.stabs	"os_tcb:T(3,11)=s96OSTCBStkPtr:(3,12)=*(4,10),0,32;OSTCBExtPtr:(3,2),32,32;OSTCBStkBottom:(3,12),64,32;OSTCBStkSize:(4,6),96,32;OSTCBOpt:(4,4),128,16;OSTCBId:(4,4),144,16;OSTCBNext:(3,13)=*(3,11),160,32;OSTCBPrev:(3,13),192,32;OSTCBEventPtr:(3,14)=*(3,6),224,32;OSTCBDly:(4,4),256,16;OSTCBStat:(4,2),272,8;OSTCBPendTO:(4,1),280,8;OSTCBPrio:(4,2),288,8;OSTCBX:(4,2),296,8;OSTCBY:(4,2),304,8;OSTCBBitX:(4,2),312,8;OSTCBBitY:(4,2),320,8;OSTCBDelReq:(4,2),328,8;OSTCBCtxSwCtr:(4,6),352,32;OSTCBCyclesTot:(4,6),384,32;OSTCBCyclesStart:(4,6),416,32;OSTCBStkBase:(3,12),448,32;OSTCBStkUsed:(4,6),480,32;OSTCBTaskName:(3,5),512,256;;",128,0,0,0
	.stabs	"OS_TCB:t(3,15)=(3,11)",128,0,464,0
	.stabn	162,0,0,0
	.stabn	162,0,0,0
	.stabn	162,0,0,0
	.stabs	"interface/usb.h",130,0,0,0
	.stabs	"EndpointDescriptorObj:t(6,1)=(6,2)=s24num:(0,1),0,32;enabled:(0,1),32,32;type:(0,1),64,32;maxpacketsize:(0,1),96,32;pid:(0,1),128,32;dir:(0,1),160,32;;",128,0,427,0
	.stabs	"IntfDescriptorObj:t(6,3)=(6,4)=s12Class:(0,1),0,32;SubClass:(0,1),32,32;Protocol:(0,1),64,32;;",128,0,433,0
	.stabs	" :T(6,5)=eMSD_BOT:0,MSD_CBI:1,;",128,0,0,0
	.stabs	"MsdDeviceType:t(6,6)=(6,5)",128,0,438,0
	.stabs	" :T(6,7)=eDISCONNECTED:0,FS_CONNECT:1,HS_CONNECT:2,LS_CONNECT:3,SUSPENDED:4,RESUMING:5,;",128,0,0,0
	.stabs	"UsbConnectionType:t(6,8)=(6,7)",128,0,447,0
	.stabs	"tUsbHostObj:t(6,9)=(6,10)=s164VID:(0,1),0,32;PID:(0,1),32,32;DevClass:(0,1),64,32;Intf:(6,3),96,96;Address:(0,1),192,32;NumEp:(0,1),224,32;enumerated:(0,1),256,32;resume_complete:(0,1),288,32;suspended:(0,1),320,32;configured:(0,1),352,32;OtgSupport:(0,1),384,32;InterfaceType:(0,1),416,32;EP0:(6,1),448,192;EPIIn:(6,1),640,192;EPBIn:(6,1),832,192;EPBOut:(6,1),1024,192;EPcsw:(6,11)=*(6,1),1216,32;connection:(6,8),1248,32;MsdType:(6,6),1280,32;;",128,0,469,0
	.stabs	" :T(6,12)=eDEFAULT:0,B_IDLE:1,B_SRP_INIT:2,B_PERIPHERAL:3,B_WAIT_ACON:4,B_HOST:5,A_IDLE:6,A_WAIT_VRISE:7,A_WAIT_BCON:8,A_HOST:9,A_HOST_REG:10,A_SUSPEND:11,A_RESUME:12,A_PERIPHERAL:13,A_WAIT_VFALL:14,A_VBUS_ERR:15,;",128,0,0,0
	.stabs	"tOtgStateType:t(6,13)=(6,12)",128,0,488,0
	.stabs	" :T(6,14)=eDEV_UNCONFIGURED:0,DEV_ADDRESSED:1,DEV_CONFIGURED:2,DEV_SUSPENDED:3,DEV_RESUME:4,HST_UNCONNECTED:5,HST_CONNECTED:6,;",128,0,0,0
	.stabs	"tUsbStateType:t(6,15)=(6,14)",128,0,498,0
	.stabs	"tOtgInfoObj:t(6,16)=(6,17)=s24SrpSupport:(0,1),0,32;HnpSupport:(0,1),32,32;hnp_enabled:(0,1),64,32;b_hnp_enable:(0,1),96,32;a_hnp_support:(0,1),128,32;a_alt_hnp_support:(0,1),160,32;;",128,0,507,0
	.stabs	"tUsbDeviceObj:t(6,18)=(6,19)=s20set_halt:(0,1),0,32;Device_Config_Value:(0,1),32,32;ep0_max_pl:(0,1),64,32;max_pl:(0,1),96,32;set_remote_wakeup:(0,1),128,32;;",128,0,515,0
	.stabs	"tUsbSystemObj:t(6,20)=(6,21)=s240DeviceState:(6,15),0,32;MainState:(6,13),32,32;otg_support:(0,1),64,32;is_host:(0,1),96,32;RegularHost:(0,1),128,32;gpout_shadow:(0,1),160,32;rxBuffer:(0,4),192,32;txBuffer:(0,4),224,32;OtgConfig:(6,16),256,192;Host:(6,9),448,1312;Dev:(6,18),1760,160;;",128,0,529,0
	.stabn	162,0,0,0
	.stabs	"interface/commandProcess.h",130,0,0,0
	.stabs	" :T(7,1)=eUSB_COMMAND_FIRMWARE_VERSION_CHECK_FAIL:-9,USB_COMMAND_FIRMWARE_UPLOAD_FAIL:-8,USB_COMMAND_FIRMWARE_SET_LENGTH_FAIL:-7,USB_COMMAND_FIRMWARE_SDRAM_WRITE_FAIL:-6,USB_COMMAND_VIDEOAPISET_FAIL:-5,USB_COMMAND_STREAM_NOT_READY:-4,USB_COMMAND_I2C_FAIL:-3,USB_COMMAND_UNDEFINED_COMMAND:-2,USB_COMMAND_FAIL:-1,USB_COMMAND_SUCCESS:0,;",128,0,0,0
	.stabs	" :T(7,2)=eINTERNAL_REGISTER_READ:16,INTERNAL_REGISTER_WRITE:17,HIF_REGISTER_READ:32,HIF_REGISTER_WRITE:33,HIF_REGISTER_BIT_SET:34,HIF_REGISTER_BIT_RESET:35,I2C_MASTER_READ:48,I2C_MASTER_WRITE:49,STREAM_GET_JPEG_LENGTH:64,STREAM_GET_H264_LENGTH:65,STREAM_GET_PCMIN_LENGTH:66,COMMAND_VIDEO_START:80,COMMAND_VIDEO_STOP:81,COMMAND_AUDIO_START:82,COMMAND_AUDIO_STOP:83,COMMAND_FIRMWARE_SDRAM_WRITE:84,COMMAND_FIRMWARE_SET_LENGTH:85,COMMAND_FIRMWARE_UPLOAD:86,COMMAND_FIRMWARE_VERSION_CHECK:87,VIDEO_API_SET:96,;",128,0,0,0
	.stabs	"VIDEO_STREAM_BUF:t(7,3)=(7,4)=s24len:(7,5)=ar(3,4);0;1;(7,6)=B(0,1),0,64;address:(7,5),64,64;full:(7,7)=ar(3,4);0;1;(7,8)=B(0,2),128,16;set_idx:(7,8),144,8;get_idx:(7,8),152,8;count:(7,8),160,8;;",128,0,55,0
	.stabs	"PCM_STREAM_BUF:t(7,9)=(7,10)=s96len:(7,11)=ar(3,4);0;9;(7,6),0,320;address:(7,11),320,320;full:(7,12)=ar(3,4);0;9;(7,8),640,80;set_idx:(7,8),720,8;get_idx:(7,8),728,8;count:(7,8),736,8;;",128,0,66,0
	.stabn	162,0,0,0
.proc _I2S_RegSet
	.stabs	"I2S_RegSet:F(0,15)",36,0,85,_I2S_RegSet
	.stabs	"reg:p(7,6)",160,0,85,-4
	.stabs	"val:P(0,1)",64,0,85,4
	.global _I2S_RegSet
	.type	_I2S_RegSet, @function
_I2S_RegSet:
	.stabd	46,0,0
	.stabn	68,0,85,.LM0-.LFBB1
.LM0:
.LFBB1:
	bg.sw    	-4(r1),r3	   # movsi store
	.stabn	68,0,86,.LM1-.LFBB1
.LM1:
	bg.lwz   	r7,-4(r1)	    # movsi load
	b.lwz   	r6,0(r7)	    # movsi load
	b.or    	r4,r4,r6
	b.sw    	0(r7),r4	   # movsi store
	.stabn	68,0,88,.LM2-.LFBB1
.LM2:
	b.jr    	r9
	.size	_I2S_RegSet, .-_I2S_RegSet
.Lscope1:
	.stabs	"",36,0,0,.Lscope1-.LFBB1
	.stabd	78,0,0
.proc _I2S_RegClr
	.stabs	"I2S_RegClr:F(0,15)",36,0,89,_I2S_RegClr
	.stabs	"reg:p(7,6)",160,0,89,-4
	.stabs	"val:P(0,1)",64,0,89,4
	.global _I2S_RegClr
	.type	_I2S_RegClr, @function
_I2S_RegClr:
	.stabd	46,0,0
	.stabn	68,0,89,.LM3-.LFBB2
.LM3:
.LFBB2:
	bg.sw    	-4(r1),r3	   # movsi store
	.stabn	68,0,90,.LM4-.LFBB2
.LM4:
	bg.lwz   	r6,-4(r1)	    # movsi load
	b.lwz   	r7,0(r6)	    # movsi load
	b.nand  	r4,r4,r4
	b.and   	r4,r4,r7
	b.sw    	0(r6),r4	   # movsi store
	.stabn	68,0,92,.LM5-.LFBB2
.LM5:
	b.jr    	r9
	.size	_I2S_RegClr, .-_I2S_RegClr
.Lscope2:
	.stabs	"",36,0,0,.Lscope2-.LFBB2
	.stabd	78,0,0
.proc _I2S_DataSize
	.stabs	"I2S_DataSize:F(0,15)",36,0,95,_I2S_DataSize
	.stabs	"reg:p(7,6)",160,0,95,-4
	.stabs	"val:P(0,1)",64,0,95,4
	.global _I2S_DataSize
	.type	_I2S_DataSize, @function
_I2S_DataSize:
	.stabd	46,0,0
	.stabn	68,0,95,.LM6-.LFBB3
.LM6:
.LFBB3:
	bg.sw    	-4(r1),r3	   # movsi store
	.stabn	68,0,96,.LM7-.LFBB3
.LM7:
	bg.lwz   	r6,-4(r1)	    # movsi load
	b.lwz   	r7,0(r6)	    # movsi load
	b.andi  	r7,r7,-458753
	b.sw    	0(r6),r7	   # movsi store
	.stabn	68,0,97,.LM8-.LFBB3
.LM8:
	bg.lwz   	r6,-4(r1)	    # movsi load
	b.lwz   	r7,0(r6)	    # movsi load
	b.or    	r4,r4,r7
	b.sw    	0(r6),r4	   # movsi store
	.stabn	68,0,99,.LM9-.LFBB3
.LM9:
	b.jr    	r9
	.size	_I2S_DataSize, .-_I2S_DataSize
.Lscope3:
	.stabs	"",36,0,0,.Lscope3-.LFBB3
	.stabd	78,0,0
.proc _I2S_IrqCnt
	.stabs	"I2S_IrqCnt:F(0,15)",36,0,101,_I2S_IrqCnt
	.stabs	"reg:p(7,6)",160,0,101,-4
	.stabs	"val:P(0,8)",64,0,101,4
	.global _I2S_IrqCnt
	.type	_I2S_IrqCnt, @function
_I2S_IrqCnt:
	.stabd	46,0,0
	.stabn	68,0,101,.LM10-.LFBB4
.LM10:
.LFBB4:
	bg.sw    	-4(r1),r3	   # movsi store
	.stabn	68,0,102,.LM11-.LFBB4
.LM11:
	bg.lwz   	r6,-4(r1)	    # movsi load
	b.lwz   	r7,0(r6)	    # movsi load
	b.andi  	r7,r7,-1024
	b.sw    	0(r6),r7	   # movsi store
	.stabn	68,0,103,.LM12-.LFBB4
.LM12:
	bg.lwz   	r6,-4(r1)	    # movsi load
	b.lwz   	r7,0(r6)	    # movsi load
	b.andi  	r4,r4,1023
	b.or    	r4,r4,r7
	b.sw    	0(r6),r4	   # movsi store
	.stabn	68,0,105,.LM13-.LFBB4
.LM13:
	b.jr    	r9
	.size	_I2S_IrqCnt, .-_I2S_IrqCnt
.Lscope4:
	.stabs	"",36,0,0,.Lscope4-.LFBB4
	.stabd	78,0,0
.proc _init_i2s
	.stabs	"init_i2s:F(0,15)",36,0,14,_init_i2s
	.global _init_i2s
	.type	_init_i2s, @function
_init_i2s:
	.stabd	46,0,0
	.stabn	68,0,14,.LM14-.LFBB5
.LM14:
.LFBB5:
	b.entri 	1,0
	.stabn	68,0,15,.LM15-.LFBB5
.LM15:
	bw.lwz   	r4,-536735504(r0)	    # movsi load
	b.andi  	r4,r4,3
	b.ori  	r3,r0,-804913152	  # movsi imm i
	b.slli  	r4,r4,21
	b.jal  	_I2S_RegSet
	.stabn	68,0,16,.LM16-.LFBB5
.LM16:
	b.ori  	r3,r0,-804913152	  # movsi imm i
	b.ori  	r4,r0,1048576	  # movsi imm i
	b.jal  	_I2S_RegSet
	.stabn	68,0,17,.LM17-.LFBB5
.LM17:
	bw.lwz   	r4,-536735504(r0)	    # movsi load
	b.slli  	r4,r4,12
	b.ori  	r3,r0,-804913152	  # movsi imm i
	b.andi  	r4,r4,458752
	b.jal  	_I2S_DataSize
	.stabn	68,0,18,.LM18-.LFBB5
.LM18:
	b.ori  	r3,r0,-804913152	  # movsi imm i
	b.addi 	r4,r0,512	  # movsi imm I
	b.jal  	_I2S_IrqCnt
	.stabn	68,0,28,.LM19-.LFBB5
.LM19:
	b.reti  	1,0
	.size	_init_i2s, .-_init_i2s
.Lscope5:
	.stabs	"",36,0,0,.Lscope5-.LFBB5
	.stabd	78,0,0
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	"!!\n\r"
.LC1:
	.string	"p\n\r"
.LC2:
	.string	"j\n\r"
.section .internalrom, "ax"
.proc _i2s_interrupt_handler
	.stabs	"i2s_interrupt_handler:F(0,15)",36,0,31,_i2s_interrupt_handler
	.global _i2s_interrupt_handler
	.type	_i2s_interrupt_handler, @function
_i2s_interrupt_handler:
	.stabd	46,0,0
	.stabn	68,0,31,.LM20-.LFBB6
.LM20:
.LFBB6:
	b.entri 	2,2
	.stabn	68,0,35,.LM21-.LFBB6
.LM21:
	bw.lwz   	r7,-804913140(r0)	    # movsi load
	b.srai  	r10,r7,16
	.stabn	68,0,36,.LM22-.LFBB6
.LM22:
	b.addi 	r6,r0,1023	  # movsi imm I
	b.bles   	r10,r6,.L12
	.stabn	68,0,38,.LM23-.LFBB6
.LM23:
	b.ori  	r3,r0,.LC0	  # movsi imm i
	b.jal  	_uart_print
.L12:
	.stabn	68,0,42,.LM24-.LFBB6
.LM24:
	bw.lbz   	r7,(_pcminDualStreamBuf+90)(r0)
	b.extbs 	r7,r7
	b.addi  	r7,r7,_pcminDualStreamBuf+80
	b.lbz   	r7,0(r7)
	b.extbs 	r7,r7
	b.beqi  	r7,0,.L14
	.stabn	68,0,44,.LM25-.LFBB6
.LM25:
	b.ori  	r3,r0,.LC1	  # movsi imm i
	b.jal  	_uart_print
	.stabn	68,0,45,.LM26-.LFBB6
.LM26:
	b.blesi  	r10,0,.L27
	bw.lwz   	r6,(_lost_pcm_len)(r0)	    # movsi load
	b.movi 	r5,0	     # movsi imm P
.L18:
	.stabn	68,0,46,.LM27-.LFBB6
.LM27:
	bw.lwz   	r7,-804909056(r0)	    # movsi load
	b.sw    	4(r1),r7	   # movsi store
	b.addi  	r6,r6,4
	.stabn	68,0,45,.LM28-.LFBB6
.LM28:
	b.addi  	r5,r5,4
	b.bgts   	r10,r5,.L18
	bw.sw    	(_lost_pcm_len)(r0),r6	   # movsi store
	b.j    	.L27
.L14:
	.stabn	68,0,53,.LM29-.LFBB6
.LM29:
	bw.lbz   	r7,(_pcminDualStreamBuf+90)(r0)
	b.extbs 	r7,r7
	b.slli  	r7,r7,2
	b.addi  	r7,r7,_pcminDualStreamBuf
	b.lwz   	r7,0(r7)	    # movsi load
	b.add   	r7,r7,r10
	b.addi 	r6,r0,3072	  # movsi imm I
	b.bles   	r7,r6,.L20
	.stabn	68,0,55,.LM30-.LFBB6
.LM30:
	b.ori  	r3,r0,.LC2	  # movsi imm i
	b.jal  	_uart_print
.L20:
	.stabn	68,0,59,.LM31-.LFBB6
.LM31:
	b.blesi  	r10,0,.L22
	b.movi 	r4,0	     # movsi imm P
	.stabn	68,0,61,.LM32-.LFBB6
.LM32:
	b.ori  	r23,r0,_pcminDualStreamBuf	  # movsi imm i
.L24:
	bw.lbz   	r6,(_pcminDualStreamBuf+90)(r0)
	b.extbs 	r6,r6
	bw.lbz   	r7,(_pcminDualStreamBuf+90)(r0)
	b.extbs 	r7,r7
	b.slli  	r7,r7,2
	b.add   	r7,r7,r23
	b.lwz   	r5,0(r7)	    # movsi load
	b.addi 	r7,r0,3072	  # movsi imm I
	b.mul   	r6,r6,r7
	b.add   	r6,r6,r5
	bw.lwz   	r7,-804909056(r0)	    # movsi load
	bw.sw    	-251559680(r6),r7	   # movsi store
	.stabn	68,0,65,.LM33-.LFBB6
.LM33:
	bw.lbz   	r7,(_pcminDualStreamBuf+90)(r0)
	b.extbs 	r7,r7
	b.slli  	r7,r7,2
	b.add   	r7,r7,r23
	b.lwz   	r6,0(r7)	    # movsi load
	b.addi  	r6,r6,4
	b.sw    	0(r7),r6	   # movsi store
	.stabn	68,0,60,.LM34-.LFBB6
.LM34:
	b.addi  	r4,r4,4
	.stabn	68,0,59,.LM35-.LFBB6
.LM35:
	b.bgts   	r10,r4,.L24
.L22:
	.stabn	68,0,67,.LM36-.LFBB6
.LM36:
	bw.lbz   	r7,(_pcminDualStreamBuf+90)(r0)
	b.extbs 	r7,r7
	b.slli  	r7,r7,2
	b.addi  	r7,r7,_pcminDualStreamBuf
	b.lwz   	r7,0(r7)	    # movsi load
	b.addi 	r6,r0,2047	  # movsi imm I
	b.bles   	r7,r6,.L27
	.stabn	68,0,69,.LM37-.LFBB6
.LM37:
	bw.lbz   	r7,(_pcminDualStreamBuf+90)(r0)
	b.extbs 	r7,r7
	b.addi  	r7,r7,_pcminDualStreamBuf+80
	b.movi  	r6,1	    # movqi imm P
	b.sb    	0(r7),r6	   # movqi store
	.stabn	68,0,70,.LM38-.LFBB6
.LM38:
	bw.lbz   	r7,(_pcminDualStreamBuf+92)(r0)
	b.addi  	r7,r7,1
	b.extbs 	r7,r7
	bw.sb    	(_pcminDualStreamBuf+92)(r0),r7	   # movqi store
	.stabn	68,0,71,.LM39-.LFBB6
.LM39:
	bw.lbz   	r7,(_pcminDualStreamBuf+90)(r0)
	b.addi  	r7,r7,1
	b.extbs 	r7,r7
	bw.sb    	(_pcminDualStreamBuf+90)(r0),r7	   # movqi store
	.stabn	68,0,72,.LM40-.LFBB6
.LM40:
	bw.lbz   	r7,(_pcminDualStreamBuf+90)(r0)
	b.extbs 	r7,r7
	b.ori  	r6,r0,10	  # movsi imm J
	b.bne   	r7,r6,.L27
	.stabn	68,0,73,.LM41-.LFBB6
.LM41:
	bw.sb    	(_pcminDualStreamBuf+90)(r0),r0	   # movqi store
.L27:
	.stabn	68,0,78,.LM42-.LFBB6
.LM42:
	b.reti  	2,2
	.size	_i2s_interrupt_handler, .-_i2s_interrupt_handler
	.stabs	"pcmDataCnt:r(0,1)",64,0,32,10
	.stabs	"pcmDataCnt_i:r(0,1)",64,0,33,5
	.stabs	"temp:(7,6)",128,0,34,4
	.stabn	192,0,0,.LFBB6-.LFBB6
	.stabn	224,0,0,.Lscope6-.LFBB6
.Lscope6:
	.stabs	"",36,0,0,.Lscope6-.LFBB6
	.stabd	78,0,0
	.global _i2s_int_enabled
.section .bss
	.align 4
	.type	_i2s_int_enabled, @object
	.size	_i2s_int_enabled, 4
_i2s_int_enabled:
	.zero	4
	.global _pcm_exist
	.align 4
	.type	_pcm_exist, @object
	.size	_pcm_exist, 4
_pcm_exist:
	.zero	4
	.global _lost_pcm_len
	.align 4
	.type	_lost_pcm_len, @object
	.size	_lost_pcm_len, 4
_lost_pcm_len:
	.zero	4
	.comm	_pEventExternalTaskDone,4,4
	.stabs	"i2s_int_enabled:G(0,1)",32,0,9,0
	.stabs	"pcm_exist:G(0,1)",32,0,10,0
	.stabs	"lost_pcm_len:G(0,1)",32,0,11,0
	.stabs	"pEventExternalTaskDone:G(3,14)",32,0,15,0
.section .internalrom, "ax"
	.stabs	"",100,0,0,.Letext0
.Letext0:
	.ident	"GCC: (GNU) 4.2.1"
